import mongoose from 'mongoose';
import { Opportunity } from './models/opportunity';

// ─── Mongoose models defined inline (Stakeholder, Task, ServiceLine, Product, User) ───

const StakeholderSchema = new mongoose.Schema(
  {
    opportunityId: { type: String, required: true },
    name: { type: String, required: true },
    title: { type: String },
    email: { type: String, default: null },
    phone: { type: String, default: null },
    linkedInUrl: { type: String, default: null },
    isPrimaryContact: { type: Boolean, default: false },
    isDecisionMaker: { type: Boolean, default: false },
    notes: { type: String, default: '' },
  },
  { timestamps: true }
);
const Stakeholder =
  mongoose.models.Stakeholder || mongoose.model('Stakeholder', StakeholderSchema);

const TaskSchema = new mongoose.Schema(
  {
    opportunityId: { type: String, required: true },
    name: { type: String, required: true },
    owner: { type: String, required: true },
    dueDate: { type: Date, required: true },
    status: { type: String, enum: ['pending', 'complete', 'overdue'], default: 'pending' },
    priority: { type: String, enum: ['Critical', 'High', 'Medium', 'Low'], default: 'Medium' },
    notes: { type: String, default: '' },
  },
  { timestamps: true }
);
const Task = mongoose.models.Task || mongoose.model('Task', TaskSchema);

const ServiceLineSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, unique: true },
    code: { type: String, required: true, unique: true },
    color: { type: String, default: '#5B4FE9' },
    isActive: { type: Boolean, default: true },
    pipelineStages: { type: [String], default: [] },
  },
  { timestamps: true }
);
const ServiceLine =
  mongoose.models.ServiceLine || mongoose.model('ServiceLine', ServiceLineSchema);

const ProductSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, unique: true },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true }
);
const Product = mongoose.models.Product || mongoose.model('Product', ProductSchema);

const UserSchema = new mongoose.Schema(
  {
    email: { type: String, required: true, unique: true },
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
    role: { type: String, enum: ['admin', 'user', 'viewer'], default: 'user' },
  },
  { timestamps: true }
);
const User = mongoose.models.User || mongoose.model('User', UserSchema);

// ─── Opportunity seed data (all 31 opportunities from v1) ───────────────────

const oppData = [
  {
    id: 'opp-001',
    customerName: 'Brightspeed',
    opportunityName: 'AI-Native Platform Transformation — PHP Modernization + Contact Center AI + DevSecOps',
    status: 'Won',
    tcv: 0,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-04-15T00:00:00.000Z'),
    startDate: new Date('2026-04-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak', 'Gaurav'],
    presalesPOCs: ['Sreeram', 'Ram'],
    industry: 'Technology',
    region: 'North America',
    source: 'Partner (Revature)',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['active-delivery', 'telecom-campaign', 'strategic'],
    conversationLog: 'Brightspeed engaged Galent via a combined pitch with Revature. SOW signed and Fieldglass registration complete. Active workstreams: (1) PHP legacy modernization, (2) Contact Center AI, (3) DevSecOps pipeline. VP Sham mandated 2 use cases delivered within 1 week — POCs confirmed within his group. Three pillars: offshore capacity, operations uplift, platform/value creation. VDOT follow-on opportunity via Transurban relationship. Revature+Galent split: 28% onshore / 72% India. Sreeram brings $350M optimization experience. IP ownership model in place. Post-TSA exit phase context. Workshop planned week of June 21.',
    activityLog: [],
  },
  {
    id: 'opp-002',
    customerName: 'Motion Industries',
    opportunityName: 'AI Platform Deployment — Pricing, Freight & Supply Chain Self-Service',
    status: 'Won',
    tcv: 0,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-04-30T00:00:00.000Z'),
    startDate: new Date('2026-04-30T00:00:00.000Z'),
    primaryOwner: 'Shankar Iyer',
    salesPOCs: ['Ashwin', 'Sreeram'],
    presalesPOCs: ['Sreeram', 'Ram'],
    industry: 'Other',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 30,
    customTags: ['active-delivery', 'platform-deployed'],
    conversationLog: 'Galent AI platform deployed. Pricing agent live April 30. Freight module in UAT. SSS Phase II planned. $8K deficit gap noted in earlier review. George Baldwin (VP of AI) has FD teams across the globe and is interested in expanding. GPC demerger opportunity — initially lost to Infosys/Cognizant but significant residual opportunity remains. Should not wait for further platform deployment to re-engage on GPC/other opportunities. Workshop planned week of June 21.',
    activityLog: [],
  },
  {
    id: 'opp-003',
    customerName: 'HNI Corporation',
    opportunityName: 'QA CoE + Project Athena RFP + Bid Wizard AI',
    status: 'Won',
    tcv: 0,
    dealDuration: '12+ months',
    expectedCloseDate: new Date('2025-12-15T00:00:00.000Z'),
    startDate: new Date('2026-01-01T00:00:00.000Z'),
    primaryOwner: 'Gaurav',
    salesPOCs: ['Gaurav', 'Sreeram'],
    presalesPOCs: ['Sreeram', 'Rehan Hanif'],
    industry: 'Manufacturing',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 29,
    customTags: ['active-delivery', 'strategic', 'workshop-june21'],
    conversationLog: 'QA CoE won December 2025. Bid Wizard AI live. Project Athena RFP pending — CMS modernization in scope. Budget clarity expected by March 13 (from Feb notes). 12% of tickets closed with no action — Galent AI opportunity for ITSM uplift. KT in progress. Workshop planned week of June 21. Meet & greet / demo week of June 15.',
    activityLog: [],
  },
  {
    id: 'opp-004',
    customerName: 'RSM',
    opportunityName: 'Development POD Model — Forward Deployed Engineering',
    status: 'Won',
    tcv: 0,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-05-01T00:00:00.000Z'),
    startDate: new Date('2026-05-15T00:00:00.000Z'),
    primaryOwner: 'Chris Wascak',
    salesPOCs: ['Chris Wascak', 'Gaurav'],
    presalesPOCs: ['Sreeram'],
    industry: 'Professional Services',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'Staffing',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 22,
    customTags: ['active-delivery', 'pod-model'],
    conversationLog: 'Dev Pods model. Pod 1 staffed. 2 pods of 3 each filled by May 15. 7 open positions total; 2-4 closures initially needed. Interviews lined up in March. CMS modernization workstream in scope. Priority client for June client visit (Ram + Vijay + Sreeram + Chris).',
    activityLog: [],
  },
  {
    id: 'opp-005',
    customerName: 'TechnoMile (Rally)',
    opportunityName: 'SIMS Infinity Replatforming — Greenfield on TechnoMile Architecture',
    status: 'Won',
    tcv: 695000,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-05-01T00:00:00.000Z'),
    startDate: new Date('2026-05-14T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak'],
    presalesPOCs: ['Sreeram', 'Ram', 'Vijay'],
    industry: 'Technology',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Fixed Price',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 27,
    customTags: ['active-delivery', 'sow-signed', 'govcloud'],
    conversationLog: 'SOW signed, initial team in place as of May 14. Greenfield replatforming of SIMS product into TechnoMile architecture. 17 modules needed by Sept 22. October 2026 Elevate conference is hard demo deadline. Strangler fig approach. AWS GovCloud + on-prem target. 190 on-prem customers. Previous engagement lost on price — BAFO resulted in 53% discount at ~$695K. On-site PM removed to reduce cost. Galent AI used as internal accelerator. Architecture session held with Pune team.',
    activityLog: [],
  },
  {
    id: 'opp-006',
    customerName: 'BlueCrest (BCC Software / Platinum Equity)',
    opportunityName: 'Java Legacy Modernization POC + App Modernization',
    status: 'Won',
    tcv: 15000,
    dealDuration: '4 months',
    expectedCloseDate: new Date('2026-04-21T00:00:00.000Z'),
    startDate: new Date('2026-04-28T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak'],
    presalesPOCs: ['Sreeram', 'Praveen Raj Mohan', 'Sanjay Venkatachar'],
    industry: 'Manufacturing',
    region: 'North America',
    source: 'Platinum Equity (PE firm)',
    serviceLine: 'IT Services',
    billingModel: 'Fixed Price',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 30,
    customTags: ['active-delivery', 'poc', 'java-modernization'],
    conversationLog: '$15K POC approved (April 21 pipeline review). 4-week POC started. Kickoff week of April 28 with Eddie coordinating. Key contact: Ganesh Seetharaman / Ganesh Sitaraman (Baltimore). Company: BlueCrest / BCC Software — sortation machine control software, 90+ developers, US/France/Poland. J2EE/JSF stack 15-20 years old. 5M lines of code across acquired codebases. Live demo ran against 819 files, 250K lines, 20-year-old telco billing system. Ganesh wants API-driven modernization strategy. Separate BCC Software thread: 5M lines of Clarion code — Galent platform supports it but no Clarion migration experience yet. Full codebase analysis recommended. Introduced via Platinum Equity; Ganesh is transferring from incumbent vendor.',
    activityLog: [],
  },
  {
    id: 'opp-007',
    customerName: 'Transurban',
    opportunityName: 'Managed Services + Express Lanes Website Modernization',
    status: 'Negotiation',
    tcv: 0,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-06-30T00:00:00.000Z'),
    startDate: new Date('2026-07-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak', 'Gaurav'],
    presalesPOCs: ['Sreeram'],
    industry: 'Other',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['msa-legal', 'workshop-june21', 'vdot-follow-on'],
    conversationLog: 'SoW defined. MSA under legal review. June 30 fiscal deadline is critical. Key contact: Japjeev Kohli (SVP Technology). Track 1: Managed services (15 tickets/month, 10x5 support). Track 2: Express Lanes website modernization, CMS upgrade. VDOT follow-on opportunity in scope. Final SOW sent February (per Feb sales review). Workshop planned week of June 21. Meet & greet / demo week of June 15.',
    activityLog: [],
  },
  {
    id: 'opp-008',
    customerName: 'Comcast',
    opportunityName: 'AI Engineering — Vendor Onboarding + AI Platform POC',
    status: 'Negotiation',
    tcv: 0,
    dealDuration: '6 months',
    expectedCloseDate: new Date('2026-06-15T00:00:00.000Z'),
    startDate: new Date('2026-07-01T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak', 'Gaurav'],
    presalesPOCs: ['Sreeram', 'Rehan Hanif'],
    industry: 'Technology',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 27,
    customTags: ['vendor-onboarding', 'legal-review', 'workshop-june21'],
    conversationLog: 'Vendor onboarding and legal in progress. AI vendor questionnaire completed (Galent AI system on AWS Bedrock, Claude Sonnet 3.5; NIST AI RMF compliant). Security plan approved; awaiting final go-ahead. 1 position expected (from March review). Internal resistance noted in February. Security plan approved per April 21 pipeline review. Workshop planned week of June 21. Can bring Comcast to the table for June workshops per Ashwin.',
    activityLog: [],
  },
  {
    id: 'opp-009',
    customerName: 'Centric',
    opportunityName: 'L1/L2 ITSM Managed Services + AI Engineering + Rebadging',
    status: 'Negotiation',
    tcv: 1215000,
    dealDuration: '24 months',
    expectedCloseDate: new Date('2026-06-15T00:00:00.000Z'),
    startDate: new Date('2026-07-01T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak'],
    presalesPOCs: ['Sreeram', 'Rehan Hanif'],
    industry: 'Technology',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Retainer',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 25,
    customTags: ['itsm', 'rebadging', 'ai-ops', 'strategic'],
    conversationLog: 'Key contact: Josh (George Kinahan). Also: Matthew Prescott, Silvana. European PXM team: Pedro, Andrew (British), Alex (Sweden). L1 pod 11 members + L2 pod 12 members. Monthly cost: $121,500 at $29.65/hr blended rate. Year 1: 15% savings, Year 2: 25% savings. Current L1 FCR ~24%, Galent target 40-50%. Incumbent: Kripya — pain points include lack of product knowledge and weak troubleshooting. Galent AI demo shown: Apple 6K alerts/day → <10% actionable. American Airlines case study: $2.4M cloud savings, 4x value. SLA tiers: Standard/Gold/Platinum. 90-day operating model.',
    activityLog: [],
  },
  {
    id: 'opp-010',
    customerName: 'Brown Advisory',
    opportunityName: 'AI Use Case POC — 24 Use Cases Under Evaluation',
    status: 'Qualification',
    tcv: 0,
    dealDuration: '3 months',
    expectedCloseDate: new Date('2026-07-15T00:00:00.000Z'),
    startDate: new Date('2026-08-01T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak'],
    presalesPOCs: ['Sreeram'],
    industry: 'Financial Services',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Fixed Price',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 30,
    customTags: ['poc-pre-commitment', 'wealth-management', 'workshop-june15'],
    conversationLog: '24 AI use cases under evaluation. POC pre-commitment stage. Baltimore location, 1 hour from DC. Meet & greet only for June 15 week (no full workshop). Included in June 15 meet & greet planning.',
    activityLog: [],
  },
  {
    id: 'opp-011',
    customerName: 'Fannie Mae',
    opportunityName: 'GenAI Platform POC',
    status: 'Proposal',
    tcv: 0,
    dealDuration: '3 months',
    expectedCloseDate: new Date('2026-06-30T00:00:00.000Z'),
    startDate: new Date('2026-07-15T00:00:00.000Z'),
    primaryOwner: 'Ashwin',
    salesPOCs: ['Ashwin', 'Sreeram'],
    presalesPOCs: ['Sreeram', 'Vijay'],
    industry: 'Financial Services',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Fixed Price',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 35,
    customTags: ['poc', 'strategic', 'all-approvals-received'],
    conversationLog: 'All approvals received (Ashwin message May 2). NDA required before POC details discussed. POC in Galent cloud environment. $0 SOW acceptable as entry point. Galent in Northern Virginia (Reston meeting possible). Contact: Sreeram Narasimhan (Fannie Mae). Executive sponsor: Shiva (CMP). Competitor: Ascendion. Citi head of vendor management pushing Galent as vendor into Fannie Mae channel. LinkedIn CDO demo scheduled May 27. Leadership demo was March 10. "Ready to proceed" per April 21 pipeline review.',
    activityLog: [],
  },
  {
    id: 'opp-012',
    customerName: 'Hughes Network Systems',
    opportunityName: 'Legacy CRM / Billing System Modernization — Full Engineering Engagement',
    status: 'Proposal',
    tcv: 930000,
    dealDuration: '36 weeks',
    expectedCloseDate: new Date('2026-06-30T00:00:00.000Z'),
    startDate: new Date('2026-07-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak', 'Gaurav'],
    presalesPOCs: ['Sreeram', 'Ram', 'Vijay'],
    industry: 'Technology',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Fixed Price',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['large-deal', 'telecom-campaign', 'workshop-june15'],
    conversationLog: 'Hughes has $9M Salesforce licensing cost — considering homegrown CRM. 25-year-old billing system targeted for microservices modernization. POC completed (demo to Hughes team). 126 features → 364 epics → 8K+ story points. 275 epics in final scope. Total cost: $930K ($850K base + $80K TPM). 36-week timeline. 11-person team (later adjusted to 3 pods). 3-person post-modernization support team at $36/hr blended. AI-native SRE with Dynatrace. Strangler fig pattern. New features in production ~week 14-15. Workshop March 12-13 held. Priority client for June client visit.',
    activityLog: [],
  },
  {
    id: 'opp-013',
    customerName: 'Briley (TalentPro HCM)',
    opportunityName: 'AI-Native HCM Platform — Country Rollout Factory + Discovery Engagement',
    status: 'Proposal',
    tcv: 100000,
    dealDuration: '3 months initial',
    expectedCloseDate: new Date('2026-06-15T00:00:00.000Z'),
    startDate: new Date('2026-07-01T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Sreeram'],
    presalesPOCs: ['Sreeram', 'Ram'],
    industry: 'Technology',
    region: 'Europe',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Fixed Price',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 30,
    customTags: ['product-engineering', 'hcm', 'country-rollout'],
    conversationLog: 'TalentPro HCM platform: 18M lines Go code, 55K files, Golang/MongoDB/Vue.js. Sri Lanka + UK expansion goals. Seed team BOT model: $100K USD/3 months. Country rollout time: 9-12 months → 3-4 months (AI-accelerated). Engineering effort down 40-50%. 4-week discovery workshop agreed. SOW within 2-3 weeks. FD architect + Forward Appointment Engineer lead. KP India visit May 4-17. 15 countries framework as target.',
    activityLog: [],
  },
  {
    id: 'opp-014',
    customerName: 'Airbus India',
    opportunityName: 'Engineering Agents Framework — Enterprise Design Assistant',
    status: 'Proposal',
    tcv: 0,
    dealDuration: '6 months initial',
    expectedCloseDate: new Date('2026-07-31T00:00:00.000Z'),
    startDate: new Date('2026-09-01T00:00:00.000Z'),
    primaryOwner: 'Ram',
    salesPOCs: ['Ashwin', 'Sreeram'],
    presalesPOCs: ['Ram', 'Vijay', 'Venkatesh', 'Murali'],
    industry: 'Manufacturing',
    region: 'APAC',
    source: 'Event (NASSCOM AI TakeOff May 21)',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 32,
    customTags: ['strategic', 'large-enterprise', 'event-sourced'],
    conversationLog: 'Galent presented at Airbus TakeOff 2026 (May 21) as invited presenter in Theme 2: Engineering Agents Framework. Internal connector: Ram Srinivasan. 3 Airbus AI initiatives: (1) Enterprise Knowledge Assistant, (2) Enterprise Design Assistant — Galent presented here, (3) Digital Twins. Key contacts: Ram Srinivasan (Airbus), Siddharth Balachandran (Innovation Center head), Pooja Narayan (AI Fast Track Leader). Airbus AI cloud spend: $46K → $181K/month. 87K+ employees trained. 2026 = "year of deployment." Follow-up actions through June 2026.',
    activityLog: [],
  },
  {
    id: 'opp-015',
    customerName: 'Wells Fargo',
    opportunityName: 'Workforce Transformation — FDE Model + AI-Native SDLC',
    status: 'Qualification',
    tcv: 0,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-07-31T00:00:00.000Z'),
    startDate: new Date('2026-09-01T00:00:00.000Z'),
    primaryOwner: 'Ashwin',
    salesPOCs: ['Ashwin', 'Sreeram'],
    presalesPOCs: ['Sreeram', 'Ram'],
    industry: 'Financial Services',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 30,
    customTags: ['strategic', 'large-enterprise', 'group-cio'],
    conversationLog: 'Group CIO meeting (Chintan Mehta) held May 4. MD prefers Galent over Revature (per April 30 BD standup). 2-3 slide deck prepared: FDE model, spec-driven dev, AI-native SDLC, knowledge graphs. Four offerings proposed: Galent native digital engineering, FDE talent, existing FTE training, upskilling at scale. Friday follow-up call scheduled.',
    activityLog: [],
  },
  {
    id: 'opp-016',
    customerName: 'ETS (Educational Testing Service)',
    opportunityName: 'Skills of the Future — Cloud Migration (MTC + Portal)',
    status: 'Won',
    tcv: 0,
    dealDuration: '4.5 months',
    expectedCloseDate: new Date('2026-03-31T00:00:00.000Z'),
    startDate: new Date('2026-03-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak'],
    presalesPOCs: ['Sreeram', 'Ram'],
    industry: 'Other',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Fixed Price',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 26,
    customTags: ['active-delivery', 'cloud-migration', 'aws'],
    conversationLog: 'Two app deployments: MTC + Portal/Pilot. AWS target: TypeScript CDK, ElastiCache, CloudWatch, Okta SSO, ECS Fargate. 4.5-month timeline targeting August 2026. Mid-March start.',
    activityLog: [],
  },
  {
    id: 'opp-017',
    customerName: 'Stellantis',
    opportunityName: 'COBOL Legacy Modernization POC + Full Engagement',
    status: 'Qualification',
    tcv: 25000,
    dealDuration: '6 months',
    expectedCloseDate: new Date('2026-06-30T00:00:00.000Z'),
    startDate: new Date('2026-07-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak', 'Gaurav'],
    presalesPOCs: ['Sreeram', 'Ram', 'Vijay'],
    industry: 'Manufacturing',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Fixed Price',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['poc', 'cobol-modernization', 'cio-transition'],
    conversationLog: 'COBOL credit card management demo: 40K lines, 101 files, 40-min analysis, risk score 7.8/10, 60% time savings vs traditional. $25-30K initial phase approved. Solution architect + DevOps + infrastructure specialist assigned. POC for 250K+ codebase. NDA expected. 6-month timeline. CIO transition underway; Q2 priorities/budgets by April-June. Pilot impressed US team (per May 7 sales call). Stellantis in AI Summit attendee list.',
    activityLog: [],
  },
  {
    id: 'opp-018',
    customerName: 'Platinum Equity / BlueCrest (ITSM)',
    opportunityName: 'ITSM Managed Services — App Modernization',
    status: 'Qualification',
    tcv: 0,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-06-30T00:00:00.000Z'),
    startDate: new Date('2026-07-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak'],
    presalesPOCs: ['Sreeram'],
    industry: 'Manufacturing',
    region: 'North America',
    source: 'Platinum Equity (PE firm)',
    serviceLine: 'IT Services',
    billingModel: 'Retainer',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 25,
    customTags: ['itsm', 'pe-portfolio'],
    conversationLog: '1,500 seats. 5 countries: UK, France, Germany, Japan, Poland. Full Microsoft stack. 1,400 incidents/month. Q2 closure target. Team estimate: 20-25 members minimum; 10-12 offshore. Need 6-12 months ITSM ticket dump for analysis. Meeting postponed. Ganesh Seetharaman (Baltimore) is key contact. Separate from BlueCrest Java modernization POC (opp-006).',
    activityLog: [],
  },
  {
    id: 'opp-019',
    customerName: 'Cognizant (US Bank RPO)',
    opportunityName: 'RPO — AI-Assisted Tech Talent Screening',
    status: 'Qualification',
    tcv: 0,
    dealDuration: '6 months',
    expectedCloseDate: new Date('2026-06-30T00:00:00.000Z'),
    startDate: new Date('2026-07-01T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Gaurav'],
    presalesPOCs: ['Sreeram'],
    industry: 'Financial Services',
    region: 'North America',
    source: 'Partner (Cognizant)',
    serviceLine: 'Staffing',
    billingModel: 'Retainer',
    clientType: 'Existing',
    opportunityType: 'Cross-sell',
    margin: 20,
    customTags: ['rpo', 'staffing', 'partner-cognizant'],
    conversationLog: 'Cognizant partnership reinstated February 15. 8 active interviews as of March 9. AI bot screening, 10-minute prescreening. 7 service areas. FNA roles (Sitco hedge fund). US Bank is the end client. Disney: 7 joiners (separate Cognizant track).',
    activityLog: [],
  },
  {
    id: 'opp-020',
    customerName: 'Colgate-Palmolive',
    opportunityName: 'AI/Digital Engineering — New Opportunity via Leadership Relationship',
    status: 'Discovery',
    tcv: 0,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-09-30T00:00:00.000Z'),
    startDate: new Date('2026-10-01T00:00:00.000Z'),
    primaryOwner: 'Ashwin',
    salesPOCs: ['Ashwin', 'Sreeram'],
    presalesPOCs: ['Sreeram'],
    industry: 'Retail',
    region: 'North America',
    source: 'Referral (friend connection)',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 30,
    customTags: ['early-pipeline', 'competitive-displacement'],
    conversationLog: 'New opportunity via friend/personal connection. Infosys is the incumbent — Galent positioning to displace them. Leadership team travel timing aligns well with June visit plan. Very initial deal but large upside.',
    activityLog: [],
  },
  {
    id: 'opp-021',
    customerName: 'Barclays',
    opportunityName: 'Wealth Management Data Platform PoV',
    status: 'On Hold',
    tcv: 0,
    dealDuration: '6 months',
    expectedCloseDate: new Date('2026-09-30T00:00:00.000Z'),
    startDate: new Date('2026-10-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Gaurav'],
    presalesPOCs: ['Sreeram', 'Rehan Hanif'],
    industry: 'Financial Services',
    region: 'Europe',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Fixed Price',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['on-hold', 'wealth-management', 'cio-change'],
    conversationLog: 'Wealth management data platform strategy PoV. Missing business drivers — key gap identified. CIO (Sree Krishna) moved to US Bank — created disruption. Opportunity stalled. Cognizant US Bank templating being evaluated as parallel track.',
    activityLog: [],
  },
  {
    id: 'opp-022',
    customerName: 'NDC Inc (Bethesda)',
    opportunityName: 'AI/Digital Engineering — Initial Meeting',
    status: 'Discovery',
    tcv: 0,
    dealDuration: '6 months',
    expectedCloseDate: new Date('2026-08-31T00:00:00.000Z'),
    startDate: new Date('2026-09-15T00:00:00.000Z'),
    primaryOwner: 'Chris Wascak',
    salesPOCs: ['Chris Wascak'],
    presalesPOCs: ['Sreeram'],
    industry: 'Other',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['early-pipeline'],
    conversationLog: 'NDC Inc, Bethesda. Meeting scheduled for week of May 19 (per May 14 sales standup). Early stage.',
    activityLog: [],
  },
  {
    id: 'opp-023',
    customerName: 'Evolver',
    opportunityName: 'AI/Digital Engineering — CIO Meeting',
    status: 'Discovery',
    tcv: 0,
    dealDuration: '6 months',
    expectedCloseDate: new Date('2026-08-31T00:00:00.000Z'),
    startDate: new Date('2026-09-15T00:00:00.000Z'),
    primaryOwner: 'Chris Wascak',
    salesPOCs: ['Chris Wascak'],
    presalesPOCs: ['Sreeram'],
    industry: 'Technology',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['early-pipeline'],
    conversationLog: 'Met CIO (per May 14 sales standup). Early stage discovery.',
    activityLog: [],
  },
  {
    id: 'opp-024',
    customerName: 'Lumen Technologies',
    opportunityName: 'Telecom AI Engineering — via Brightspeed Relationship',
    status: 'Discovery',
    tcv: 0,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-09-30T00:00:00.000Z'),
    startDate: new Date('2026-10-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak'],
    presalesPOCs: ['Sreeram'],
    industry: 'Technology',
    region: 'North America',
    source: 'Referral (Brightspeed relationship)',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['early-pipeline', 'telecom-campaign'],
    conversationLog: 'Lumen Technologies via Brightspeed relationship. Part of broader telecom campaign (May 26 telecom followup). Shifting to US-based stakeholders. Infosys Topaz competing in upskilling.',
    activityLog: [],
  },
  {
    id: 'opp-025',
    customerName: 'Telstra',
    opportunityName: 'Telecom AI Engineering — via Infosys Contact',
    status: 'Discovery',
    tcv: 0,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-09-30T00:00:00.000Z'),
    startDate: new Date('2026-10-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak'],
    presalesPOCs: ['Sreeram'],
    industry: 'Technology',
    region: 'APAC',
    source: 'Referral (Infosys contact)',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['early-pipeline', 'telecom-campaign'],
    conversationLog: 'Telstra via Infosys contact (May 26 telecom followup). Part of broader telecom campaign targeting APAC telecom sector.',
    activityLog: [],
  },
  {
    id: 'opp-026',
    customerName: 'Rakuten',
    opportunityName: 'AI Engineering / Managed Services — MSA Stalled',
    status: 'On Hold',
    tcv: 0,
    dealDuration: '12 months',
    expectedCloseDate: new Date('2026-07-31T00:00:00.000Z'),
    startDate: new Date('2026-08-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Chris Wascak', 'Gaurav'],
    presalesPOCs: ['Sreeram'],
    industry: 'Retail',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 27,
    customTags: ['stalled', 'msa-pending'],
    conversationLog: 'Moving slow per Feb 2026 pipeline review. 70-80% MSA completion stalled (per May 6 telecom follow-up). Engagement needed to unblock.',
    activityLog: [],
  },
  {
    id: 'opp-027',
    customerName: 'Galaxy',
    opportunityName: 'AI/Digital Engineering — Initial Meeting',
    status: 'Discovery',
    tcv: 0,
    dealDuration: '6 months',
    expectedCloseDate: new Date('2026-08-31T00:00:00.000Z'),
    startDate: new Date('2026-09-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Gaurav'],
    presalesPOCs: ['Sreeram'],
    industry: 'Other',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['early-pipeline'],
    conversationLog: 'Galaxy meeting scheduled March 12 (per Feb 26 pipeline review). Early stage.',
    activityLog: [],
  },
  {
    id: 'opp-028',
    customerName: 'FYNDNA / FynDNA',
    opportunityName: 'AI Banking Platform — Services-First Approach',
    status: 'Discovery',
    tcv: 0,
    dealDuration: '3 months',
    expectedCloseDate: new Date('2026-07-31T00:00:00.000Z'),
    startDate: new Date('2026-08-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Gaurav'],
    presalesPOCs: ['Sreeram', 'Rehan Hanif'],
    industry: 'Financial Services',
    region: 'APAC',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Fixed Price',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['early-pipeline', 'fintech'],
    conversationLog: 'Services-first approach. Platform demo capped at 30 min. FynDNA is a low-code/no-code banking platform for HDFC. Meeting Thursday (per Feb 9 BD standup). Deck in progress.',
    activityLog: [],
  },
  {
    id: 'opp-029',
    customerName: 'Highmark',
    opportunityName: 'AI CoE / Enterprise Platform Assessment',
    status: 'Discovery',
    tcv: 0,
    dealDuration: '6 months',
    expectedCloseDate: new Date('2026-08-31T00:00:00.000Z'),
    startDate: new Date('2026-09-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Gaurav'],
    presalesPOCs: ['Sreeram'],
    industry: 'Healthcare',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['early-pipeline', 'healthcare', 'ai-coe'],
    conversationLog: 'Highmark AI CoE and enterprise platform assessment. Mentioned in Feb 2 daily note and internal sync on FYNDNA/Engen/HighMark meeting.',
    activityLog: [],
  },
  {
    id: 'opp-030',
    customerName: 'Skyworks Solutions',
    opportunityName: 'Digital Engineering — MSA Sharing Stage',
    status: 'Discovery',
    tcv: 0,
    dealDuration: '6 months',
    expectedCloseDate: new Date('2026-07-31T00:00:00.000Z'),
    startDate: new Date('2026-08-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Gaurav', 'Chris Wascak'],
    presalesPOCs: ['Sreeram'],
    industry: 'Technology',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['early-pipeline'],
    conversationLog: 'MSA sharing stage (per March 4 solutioning & bid team note). AI Summit attendee invitation confirmed.',
    activityLog: [],
  },
  {
    id: 'opp-031',
    customerName: 'Sun Life Financial',
    opportunityName: 'Digital Engineering — Elevator Pitch Stage',
    status: 'Discovery',
    tcv: 0,
    dealDuration: '6 months',
    expectedCloseDate: new Date('2026-08-31T00:00:00.000Z'),
    startDate: new Date('2026-09-15T00:00:00.000Z'),
    primaryOwner: 'Sreeram',
    salesPOCs: ['Gaurav', 'Chris Wascak'],
    presalesPOCs: ['Sreeram'],
    industry: 'Financial Services',
    region: 'North America',
    source: 'Direct',
    serviceLine: 'IT Services',
    billingModel: 'Time & Material',
    clientType: 'New',
    opportunityType: 'New Deal',
    margin: 28,
    customTags: ['early-pipeline'],
    conversationLog: 'Elevator pitch stage (per March 4 solutioning & bid team note).',
    activityLog: [],
  },
];

// ─── Stakeholder seed data ──────────────────────────────────────────────────

const stakeholderData = [
  { opportunityId: 'opp-001', name: 'Sham', title: 'VP (Mandate Owner)', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: true, notes: 'Mandated 2 POC use cases within 1 week. Champion for Galent engagement.' },
  { opportunityId: 'opp-002', name: 'George Baldwin', title: 'VP of AI', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: true, notes: 'Has FD teams across the globe. Interested in expanding use of Galent FD team model. Should engage independently of platform deployment.' },
  { opportunityId: 'opp-002', name: 'Shankar', title: 'Platform Owner', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'Oversees platform deployment. Check with Shankar on Motion platform status.' },
  { opportunityId: 'opp-003', name: 'Gaurav', title: 'Galent Account Owner', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: false, notes: 'Awaiting feedback on HNI QA CoE expansion. Feedback due per Feb 9 standup.' },
  { opportunityId: 'opp-005', name: 'TechnoMile Leadership', title: 'Executive Team', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: true, notes: 'SOW signed. Hard deadline: October 2026 Elevate conference. 190 on-prem customer base.' },
  { opportunityId: 'opp-006', name: 'Ganesh Seetharaman', title: 'Technical Lead / Client Contact', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: true, notes: 'Baltimore-based. Wants API-driven modernization strategy. Coordinating POC via Eddie.' },
  { opportunityId: 'opp-006', name: 'Victor', title: 'BCC Software Internal Contact', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'BCC Software (Clarion track). Will discuss full codebase analysis internally.' },
  { opportunityId: 'opp-006', name: 'Praveen Raj Mohan', title: 'Galent Delivery Lead', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'Assigned to BlueCrest Java modernization POC.' },
  { opportunityId: 'opp-006', name: 'Sanjay Venkatachar', title: 'Galent Technical Lead', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'Assigned to BlueCrest Java modernization POC.' },
  { opportunityId: 'opp-007', name: 'Japjeev Kohli', title: 'SVP Technology', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: true, notes: 'Primary executive contact at Transurban. June 30 fiscal deadline is critical for SOW execution.' },
  { opportunityId: 'opp-009', name: 'Josh (George Kinahan)', title: 'Client Executive', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: true, notes: 'Wants cost savings model. ACI use case as template.' },
  { opportunityId: 'opp-009', name: 'Matthew Prescott', title: 'Technical Contact', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'On call with Josh and Silvana.' },
  { opportunityId: 'opp-009', name: 'Silvana', title: 'Business Contact', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'On call with Josh and Matthew.' },
  { opportunityId: 'opp-009', name: 'Pedro', title: 'European PXM Team Lead', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'European PXM team. Needs concrete pain point identification. Start with AI dev tools.' },
  { opportunityId: 'opp-009', name: 'Andrew', title: 'European PXM Team (UK)', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'British member of European PXM team.' },
  { opportunityId: 'opp-009', name: 'Alex', title: 'European PXM Team (Sweden)', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'Sweden member of European PXM team.' },
  { opportunityId: 'opp-011', name: 'Sreeram Narasimhan', title: 'Contact (Fannie Mae)', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: false, notes: 'Primary contact at Fannie Mae for POC coordination.' },
  { opportunityId: 'opp-011', name: 'Shiva', title: 'Executive Sponsor (CMP)', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: true, notes: 'Executive sponsor at Fannie Mae for the Galent GenAI platform POC.' },
  { opportunityId: 'opp-012', name: 'Hughes Leadership', title: 'Client Executive Team', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: true, notes: 'Engaged through workshop March 12-13. Reviewing $930K proposal. Need to close before June visit.' },
  { opportunityId: 'opp-014', name: 'Ram Srinivasan', title: 'Internal Connector (Airbus India)', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: false, notes: 'Galent internal connector at Airbus. Key relationship for TakeOff follow-up.' },
  { opportunityId: 'opp-014', name: 'Siddharth Balachandran', title: 'Head of Innovation Center', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: true, notes: 'Airbus India Innovation Center head. Key decision-maker for engineering AI initiatives.' },
  { opportunityId: 'opp-014', name: 'Pooja Narayan', title: 'AI Fast Track Leader', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'Airbus AI strategy lead. 4-quadrant AI strategy, GCP+Gemini+Claude as natural partner.' },
  { opportunityId: 'opp-015', name: 'Chintan Mehta', title: 'Group CIO', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: true, notes: 'Group CIO meeting held May 4. Deck prepared: FDE model, spec-driven dev, AI-native SDLC.' },
  { opportunityId: 'opp-017', name: 'Stellantis CIO (New)', title: 'CIO', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: true, notes: 'CIO transition underway. Q2 priorities/budgets being set April-June. NDA expected.' },
  { opportunityId: 'opp-017', name: 'Global Program Lead', title: 'Global Program Lead', email: null, phone: null, linkedInUrl: null, isPrimaryContact: false, isDecisionMaker: false, notes: 'Follow-up pending per March engagement plan.' },
  { opportunityId: 'opp-018', name: 'Ganesh Seetharaman', title: 'Technical Contact (Baltimore)', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: false, notes: 'Shared contact with BlueCrest Java track. Focus here is ITSM managed services.' },
  { opportunityId: 'opp-020', name: 'Ashwin Contact', title: 'Friend / Referral', email: null, phone: null, linkedInUrl: null, isPrimaryContact: true, isDecisionMaker: false, notes: 'Friend connection. Infosys incumbent. Leadership travel timing aligns with June visit.' },
];

// ─── Task seed data ─────────────────────────────────────────────────────────

const taskData = [
  { opportunityId: 'opp-001', name: 'Register on Fieldglass supplier portal', owner: 'Chris Wascak', dueDate: new Date('2026-05-02T00:00:00.000Z'), status: 'complete', priority: 'Critical', notes: 'Fieldglass registration confirmed complete per April 30 BD standup.' },
  { opportunityId: 'opp-001', name: 'Deliver 2 POC use cases for VP Sham', owner: 'Sreeram', dueDate: new Date('2026-05-13T00:00:00.000Z'), status: 'complete', priority: 'Critical', notes: '2 POCs confirmed within Sham group per May 14 standup.' },
  { opportunityId: 'opp-001', name: 'Schedule June 15 meet & greet and June 21 workshop', owner: 'Sreeram', dueDate: new Date('2026-06-05T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Lock dates on calendar per Ashwin guidance. First week meet & greet, second week workshop.' },
  { opportunityId: 'opp-001', name: 'Explore VDOT follow-on via Transurban relationship', owner: 'Chris Wascak', dueDate: new Date('2026-07-01T00:00:00.000Z'), status: 'pending', priority: 'Medium', notes: 'VDOT opportunity mentioned in telecom campaign follow-up.' },
  { opportunityId: 'opp-002', name: 'Re-engage George Baldwin on FD teams opportunity', owner: 'Sreeram', dueDate: new Date('2026-06-07T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Do not wait for platform deployment. GPC demerger residual opportunity also in play.' },
  { opportunityId: 'opp-002', name: 'Schedule detailed conversation with Motion leadership', owner: 'Sreeram', dueDate: new Date('2026-06-10T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Ashwin directive: should not wait for platform alone — other opportunities exist.' },
  { opportunityId: 'opp-002', name: 'Schedule June 21 workshop', owner: 'Sreeram', dueDate: new Date('2026-06-05T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Workshop week of June 21.' },
  { opportunityId: 'opp-003', name: 'Schedule June 15 meet & greet / demo', owner: 'Sreeram', dueDate: new Date('2026-06-05T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'First week meet & greet and demos. Second week (June 21) full workshop.' },
  { opportunityId: 'opp-003', name: 'Define Project Athena RFP response approach', owner: 'Sreeram', dueDate: new Date('2026-06-10T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'CMS modernization RFP pending. Prep with Rehan Hanif.' },
  { opportunityId: 'opp-003', name: 'Prepare 15-min customer agenda for workshop week', owner: 'Sreeram', dueDate: new Date('2026-06-08T00:00:00.000Z'), status: 'pending', priority: 'Medium', notes: 'Per Ashwin: 15 minutes per customer to define agenda and materials before workshop week.' },
  { opportunityId: 'opp-005', name: 'Complete 17-module delivery by Sept 22', owner: 'Ram', dueDate: new Date('2026-09-22T00:00:00.000Z'), status: 'pending', priority: 'Critical', notes: 'Hard deadline for Elevate conference demo October 2026.' },
  { opportunityId: 'opp-005', name: 'Architecture session with Pune team', owner: 'Vijay', dueDate: new Date('2026-05-30T00:00:00.000Z'), status: 'complete', priority: 'High', notes: 'Architecture session completed per April 7 Q&A clarifications note.' },
  { opportunityId: 'opp-006', name: 'Complete 4-week Java modernization POC', owner: 'Praveen Raj Mohan', dueDate: new Date('2026-05-26T00:00:00.000Z'), status: 'complete', priority: 'Critical', notes: '4-week POC started end of April. Kickoff coordinated by Eddie.' },
  { opportunityId: 'opp-006', name: 'Present POC results and scope full engagement', owner: 'Sreeram', dueDate: new Date('2026-06-07T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Ganesh wants API-driven strategy. Expand from POC to full app modernization engagement.' },
  { opportunityId: 'opp-006', name: 'BCC Software: pursue Clarion codebase analysis', owner: 'Sreeram', dueDate: new Date('2026-06-15T00:00:00.000Z'), status: 'pending', priority: 'Medium', notes: 'Victor to discuss internally. 5M lines Clarion code. Recommend full codebase analysis.' },
  { opportunityId: 'opp-007', name: 'Close MSA legal review before June 30 fiscal deadline', owner: 'Sreeram', dueDate: new Date('2026-06-25T00:00:00.000Z'), status: 'pending', priority: 'Critical', notes: 'June 30 fiscal deadline is hard. MSA under legal review. Engage Japjeev Kohli directly.' },
  { opportunityId: 'opp-007', name: 'Schedule June 21 workshop', owner: 'Sreeram', dueDate: new Date('2026-06-05T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Workshop week of June 21 per Ashwin plan.' },
  { opportunityId: 'opp-008', name: 'Receive final go-ahead post security plan approval', owner: 'Chris Wascak', dueDate: new Date('2026-06-10T00:00:00.000Z'), status: 'pending', priority: 'Critical', notes: 'Security plan approved. Awaiting final go-ahead. Vendor onboarding / legal in final stage.' },
  { opportunityId: 'opp-008', name: 'Schedule June 21 workshop', owner: 'Sreeram', dueDate: new Date('2026-06-05T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Can bring Comcast to workshop table for June 21 week per Ashwin.' },
  { opportunityId: 'opp-009', name: 'Schedule dedicated Galent AI demo session', owner: 'Sreeram', dueDate: new Date('2026-06-07T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Josh/team want separate deep-dive on Galent AI capabilities.' },
  { opportunityId: 'opp-009', name: 'Identify concrete pain points with Pedro and Andrew', owner: 'Rehan Hanif', dueDate: new Date('2026-06-10T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Start with AI dev tools. American Airlines case study as reference.' },
  { opportunityId: 'opp-009', name: 'Finalize 90-day operating model and SOW', owner: 'Sreeram', dueDate: new Date('2026-06-15T00:00:00.000Z'), status: 'pending', priority: 'Critical', notes: 'L1+L2 pod structure, $121,500/month, SLA tiers Standard/Gold/Platinum.' },
  { opportunityId: 'opp-010', name: 'Schedule June 15 meet & greet (Baltimore)', owner: 'Sreeram', dueDate: new Date('2026-06-05T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Meet & greet only — no full workshop. Baltimore location, 1 hour away. Plan local visit.' },
  { opportunityId: 'opp-010', name: 'Define POC scope for top 3-5 of 24 use cases', owner: 'Sreeram', dueDate: new Date('2026-06-20T00:00:00.000Z'), status: 'pending', priority: 'Medium', notes: 'Pre-commitment stage. Prioritize use cases for POC proposal.' },
  { opportunityId: 'opp-011', name: 'Execute NDA', owner: 'Ashwin', dueDate: new Date('2026-06-07T00:00:00.000Z'), status: 'pending', priority: 'Critical', notes: 'NDA required before POC details shared. All internal approvals received.' },
  { opportunityId: 'opp-011', name: 'Set up POC environment in Galent cloud', owner: 'Vijay', dueDate: new Date('2026-06-15T00:00:00.000Z'), status: 'pending', priority: 'High', notes: '$0 SOW acceptable. POC runs in Galent cloud environment.' },
  { opportunityId: 'opp-011', name: 'CDO LinkedIn demo follow-up', owner: 'Ashwin', dueDate: new Date('2026-06-01T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'CDO demo was May 27. Follow up with next steps.' },
  { opportunityId: 'opp-012', name: 'Follow up on $930K proposal — get decision', owner: 'Sreeram', dueDate: new Date('2026-06-15T00:00:00.000Z'), status: 'pending', priority: 'Critical', notes: 'Proposal submitted. Need decision before June client visits. Workshop week of June 15.' },
  { opportunityId: 'opp-012', name: 'Schedule June 15 workshop / customer visit', owner: 'Chris Wascak', dueDate: new Date('2026-06-05T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Priority client for June visit per May 7 sales leadership call.' },
  { opportunityId: 'opp-013', name: 'Schedule discovery kick-off', owner: 'Sreeram', dueDate: new Date('2026-06-07T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Discovery kick-off scheduling as of May 3 daily note. 4-week discovery workshop agreed.' },
  { opportunityId: 'opp-013', name: 'Finalize SOW for discovery engagement', owner: 'Sreeram', dueDate: new Date('2026-06-15T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'SOW within 2-3 weeks of agreement. FD architect + Forward Appointment Engineer lead.' },
  { opportunityId: 'opp-014', name: 'Follow up with Siddharth Balachandran post-TakeOff event', owner: 'Ram', dueDate: new Date('2026-06-07T00:00:00.000Z'), status: 'pending', priority: 'Critical', notes: 'Follow-up actions committed through June 2026 from TakeOff event May 21.' },
  { opportunityId: 'opp-014', name: 'Prepare Engineering Agents Framework proposal', owner: 'Ram', dueDate: new Date('2026-06-21T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Theme 2: Enterprise Design Assistant. Pitch materials available. Venkatesh + Murali support.' },
  { opportunityId: 'opp-015', name: 'Follow up on Group CIO meeting (Chintan Mehta)', owner: 'Ashwin', dueDate: new Date('2026-06-07T00:00:00.000Z'), status: 'pending', priority: 'High', notes: '2-3 slide deck presented. FDE model, spec-driven dev, AI-native SDLC. Follow up on next steps.' },
  { opportunityId: 'opp-016', name: 'Complete MTC + Portal cloud deployment (AWS)', owner: 'Ram', dueDate: new Date('2026-08-31T00:00:00.000Z'), status: 'pending', priority: 'Critical', notes: 'Targeting August 2026. TypeScript CDK, ElastiCache, CloudWatch, Okta SSO, ECS Fargate.' },
  { opportunityId: 'opp-017', name: 'Pursue NDA execution with new CIO team', owner: 'Sreeram', dueDate: new Date('2026-06-15T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'CIO transition creates opening. Q2 budgets being set now. NDA expected.' },
  { opportunityId: 'opp-017', name: 'Draft POC expansion proposal for 250K+ codebase', owner: 'Sreeram', dueDate: new Date('2026-06-20T00:00:00.000Z'), status: 'pending', priority: 'High', notes: '$25-30K pilot approved. Draft full engagement proposal for CIO review.' },
  { opportunityId: 'opp-019', name: 'Progress 2-4 closures from 7 open positions at RSM', owner: 'Gaurav', dueDate: new Date('2026-06-10T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Interviews lined up. 2-4 closures needed per Feb 17 pipeline review.' },
  { opportunityId: 'opp-020', name: 'Coordinate in-person meeting during leadership travel', owner: 'Ashwin', dueDate: new Date('2026-06-21T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'Friend said leadership travel timing is ideal for in-person intro. Displacement of Infosys.' },
  { opportunityId: 'opp-026', name: 'Unblock 70-80% complete MSA', owner: 'Sreeram', dueDate: new Date('2026-06-15T00:00:00.000Z'), status: 'pending', priority: 'High', notes: 'MSA stalled. Identify blocker and push to closure.' },
];

// ─── Main seed function ─────────────────────────────────────────────────────

export async function seed() {
  const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/galent';
  console.log(`[seed] Connecting to MongoDB at ${MONGODB_URI}...`);
  await mongoose.connect(MONGODB_URI);
  console.log('[seed] Connected.');

  // Check if data already exists
  const existingCount = await Opportunity.countDocuments();
  if (existingCount > 0 && process.env.FORCE_RESEED !== 'true') {
    console.log(`[seed] Database already has ${existingCount} opportunities — skipping seed.`);
    await mongoose.disconnect();
    return;
  }

  if (process.env.FORCE_RESEED === 'true') {
    console.log('[seed] FORCE_RESEED=true — clearing and reseeding...');
    await Opportunity.deleteMany({});
    await Stakeholder.deleteMany({});
    await Task.deleteMany({});
    await ServiceLine.deleteMany({});
    await Product.deleteMany({});
    await User.deleteMany({});
    console.log('[seed] Cleared all existing data.');
  } else {
    console.log('[seed] Empty database detected — seeding Galent pipeline data...');
  }

  // 1. Seed opportunities
  console.log('[seed] Inserting opportunities...');
  await Opportunity.insertMany(oppData);
  console.log(`[seed] ${oppData.length} opportunities inserted.`);

  // 2. Seed stakeholders
  console.log('[seed] Inserting stakeholders...');
  await Stakeholder.insertMany(stakeholderData);
  console.log(`[seed] ${stakeholderData.length} stakeholders inserted.`);

  // 3. Seed tasks
  console.log('[seed] Inserting tasks...');
  await Task.insertMany(taskData);
  console.log(`[seed] ${taskData.length} tasks inserted.`);

  // 4. Seed service lines
  console.log('[seed] Inserting service lines...');
  const serviceLineData = [
    {
      name: 'IT Services',
      code: 'ITS',
      color: '#5B4FE9',
      isActive: true,
      pipelineStages: ['Discovery', 'Qualification', 'Solutioning', 'Proposal', 'Negotiation', 'Won', 'Lost', 'On Hold'],
    },
    {
      name: 'Staffing',
      code: 'STF',
      color: '#00dc82',
      isActive: true,
      pipelineStages: ['Requirement', 'Sourcing', 'Submission', 'Interview', 'Offer', 'Placement', 'Lost'],
    },
  ];
  await ServiceLine.insertMany(serviceLineData);
  console.log(`[seed] ${serviceLineData.length} service lines inserted.`);

  // 5. Seed products
  console.log('[seed] Inserting products...');
  const productNames = [
    'AI Platform',
    'QA CoE',
    'DevSecOps',
    'Cloud Migration',
    'Data Analytics',
    'Contact Center AI',
  ];
  const productData = productNames.map((name) => ({ name, isActive: true }));
  await Product.insertMany(productData);
  console.log(`[seed] ${productData.length} products inserted.`);

  // 6. Seed default admin user
  console.log('[seed] Inserting default admin user...');
  await User.create({
    email: 'admin@galent.com',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
  });
  console.log('[seed] Admin user created (admin@galent.com).');

  // 7. Seed engagement types
  const { seedEngagementTypes } = await import('./seed-engagement-types');
  await seedEngagementTypes();

  console.log('[seed] Seeding complete.');
  await mongoose.disconnect();
}
