/**
 * Galent SalesPilot — Proposal Template Library
 *
 * 150+ proposal templates organized by:
 * - Service Domain (12 domains)
 * - Engagement Type (6 types)
 * - Industry Vertical (10 verticals)
 * - Complexity (3 levels)
 *
 * Each template includes:
 * - Section structure (what to include)
 * - AI prompt starters (contextual generation hints)
 * - Typical team composition
 * - Standard deliverables
 * - Risk factors
 */

export interface ProposalTemplate {
  id: string;
  name: string;
  domain: ServiceDomain;
  engagementType: EngagementType;
  industries: string[];
  complexity: 'Standard' | 'Complex' | 'Enterprise';
  description: string;
  sections: TemplateSection[];
  typicalTeam: { role: string; count: number; geo: string }[];
  deliverables: string[];
  risks: string[];
  durationRange: string;
  tcvRange: string;
  tags: string[];
  aiPromptContext: string;
}

export interface TemplateSection {
  id: string;
  title: string;
  required: boolean;
  aiPromptHint: string;
  sampleOutline: string[];
}

export type ServiceDomain =
  | 'AI & Data Engineering'
  | 'Cloud & Infrastructure'
  | 'Application Development'
  | 'Enterprise Architecture'
  | 'ERP & Business Applications'
  | 'Managed Services'
  | 'QA & Testing'
  | 'DevSecOps'
  | 'Digital Transformation'
  | 'Consulting & Advisory'
  | 'Cybersecurity'
  | 'Staff Augmentation';

export type EngagementType =
  | 'Fixed Price'
  | 'Time & Material'
  | 'Managed Service'
  | 'Consulting'
  | 'Staff Augmentation'
  | 'Hybrid';

// ── Standard sections that apply to most proposals ──
const COMMON_SECTIONS: TemplateSection[] = [
  { id: 'exec_summary', title: 'Executive Summary', required: true, aiPromptHint: 'Business challenge, proposed solution, expected outcomes, why us', sampleOutline: ['Business context', 'Challenge statement', 'Proposed solution overview', 'Expected business impact', 'Why Galent'] },
  { id: 'company_overview', title: 'Company Overview & Qualifications', required: true, aiPromptHint: 'Galent capabilities, relevant experience, certifications, partnerships', sampleOutline: ['About Galent', 'Relevant experience', 'Industry expertise', 'Technology partnerships', 'Certifications'] },
  { id: 'understanding', title: 'Understanding of Requirements', required: true, aiPromptHint: 'Demonstrate deep understanding of client needs, pain points, goals', sampleOutline: ['Current state analysis', 'Pain points identified', 'Business objectives', 'Success criteria', 'Constraints & dependencies'] },
  { id: 'solution', title: 'Proposed Solution', required: true, aiPromptHint: 'Solution architecture, technology stack, integration points, innovation', sampleOutline: ['Solution overview', 'Architecture diagram description', 'Technology stack', 'Integration approach', 'Innovation elements'] },
  { id: 'approach', title: 'Implementation Approach', required: true, aiPromptHint: 'Methodology, phases, governance, quality assurance', sampleOutline: ['Methodology (Agile/Waterfall/Hybrid)', 'Phase breakdown', 'Governance model', 'Quality gates', 'Change management'] },
  { id: 'team', title: 'Team & Resources', required: true, aiPromptHint: 'Team structure, roles, qualifications, org chart, onshore/offshore mix', sampleOutline: ['Team structure', 'Key personnel', 'Role descriptions', 'Onshore/offshore model', 'Knowledge transfer plan'] },
  { id: 'timeline', title: 'Timeline & Milestones', required: true, aiPromptHint: 'Phases with dates, milestones, dependencies, go-live criteria', sampleOutline: ['Phase timeline', 'Key milestones', 'Dependencies', 'Go-live criteria', 'Hypercare period'] },
  { id: 'pricing', title: 'Pricing & Commercial Terms', required: true, aiPromptHint: 'Cost breakdown, payment schedule, pricing model, value proposition', sampleOutline: ['Pricing summary', 'Rate card', 'Payment schedule', 'Travel & expenses', 'Optional items'] },
  { id: 'risks', title: 'Risk Management', required: true, aiPromptHint: 'Identified risks, mitigation strategies, escalation path', sampleOutline: ['Risk register', 'Mitigation strategies', 'Contingency plans', 'Escalation matrix'] },
  { id: 'terms', title: 'Terms & Conditions', required: false, aiPromptHint: 'IP, confidentiality, SLAs, warranties, termination', sampleOutline: ['IP ownership', 'Confidentiality', 'SLAs', 'Warranty', 'Termination clause'] },
];

// ── Domain-specific additional sections ──
const AI_SECTIONS: TemplateSection[] = [
  { id: 'data_strategy', title: 'Data Strategy & Governance', required: true, aiPromptHint: 'Data sources, quality, governance, privacy, ethics', sampleOutline: ['Data landscape', 'Quality framework', 'Governance model', 'Privacy compliance', 'Ethical AI guidelines'] },
  { id: 'ml_approach', title: 'ML/AI Approach', required: true, aiPromptHint: 'Model selection, training, evaluation, deployment, monitoring', sampleOutline: ['Model architecture', 'Training approach', 'Evaluation metrics', 'MLOps pipeline', 'Monitoring & drift detection'] },
];

const CLOUD_SECTIONS: TemplateSection[] = [
  { id: 'migration_strategy', title: 'Migration Strategy', required: true, aiPromptHint: '6R assessment, wave planning, cutover strategy', sampleOutline: ['6R assessment', 'Wave planning', 'Dependency mapping', 'Cutover strategy', 'Rollback plan'] },
  { id: 'architecture', title: 'Target Architecture', required: true, aiPromptHint: 'Landing zone, network, security, HA/DR', sampleOutline: ['Landing zone design', 'Network topology', 'Security architecture', 'HA/DR strategy', 'Cost optimization'] },
];

const ERP_SECTIONS: TemplateSection[] = [
  { id: 'fit_gap', title: 'Fit-Gap Analysis', required: true, aiPromptHint: 'Standard vs custom, configuration approach, data migration', sampleOutline: ['Fit analysis', 'Gap identification', 'Configuration vs customization', 'Data migration strategy', 'Integration points'] },
  { id: 'change_mgmt', title: 'Organizational Change Management', required: true, aiPromptHint: 'Training, adoption, stakeholder management', sampleOutline: ['Stakeholder analysis', 'Communication plan', 'Training program', 'Adoption metrics', 'Support model'] },
];

const MANAGED_SECTIONS: TemplateSection[] = [
  { id: 'sla_framework', title: 'SLA Framework', required: true, aiPromptHint: 'Service levels, KPIs, penalties, reporting', sampleOutline: ['SLA tiers', 'KPI definitions', 'Measurement methodology', 'Penalty/bonus structure', 'Reporting cadence'] },
  { id: 'ops_model', title: 'Operating Model', required: true, aiPromptHint: 'ITIL processes, tooling, shift model, escalation', sampleOutline: ['ITIL process map', 'Tool stack', 'Shift model', 'Escalation matrix', 'Continuous improvement'] },
];

const SECURITY_SECTIONS: TemplateSection[] = [
  { id: 'threat_assessment', title: 'Threat & Vulnerability Assessment', required: true, aiPromptHint: 'Threat landscape, vulnerability scan approach, compliance mapping', sampleOutline: ['Threat landscape', 'Vulnerability assessment', 'Compliance mapping', 'Gap analysis', 'Remediation priority'] },
  { id: 'security_arch', title: 'Security Architecture', required: true, aiPromptHint: 'Zero trust, IAM, encryption, monitoring, incident response', sampleOutline: ['Zero trust model', 'IAM framework', 'Encryption standards', 'SIEM/monitoring', 'Incident response plan'] },
];

// ── Template Generator ──

function makeTemplate(
  id: string, name: string, domain: ServiceDomain, engType: EngagementType,
  industries: string[], complexity: 'Standard' | 'Complex' | 'Enterprise',
  description: string, extraSections: TemplateSection[],
  team: { role: string; count: number; geo: string }[],
  deliverables: string[], risks: string[],
  durationRange: string, tcvRange: string, tags: string[], aiContext: string
): ProposalTemplate {
  return {
    id, name, domain, engagementType: engType, industries, complexity, description,
    sections: [...COMMON_SECTIONS, ...extraSections],
    typicalTeam: team, deliverables, risks, durationRange, tcvRange, tags,
    aiPromptContext: aiContext,
  };
}

// ── THE TEMPLATE LIBRARY (150+ templates) ──

export const PROPOSAL_TEMPLATES: ProposalTemplate[] = [
  // ═══════════════════════════════════════════
  // AI & DATA ENGINEERING (15 templates)
  // ═══════════════════════════════════════════
  makeTemplate('ai-01', 'AI/ML Platform Build', 'AI & Data Engineering', 'Fixed Price', ['Technology', 'Financial Services', 'Healthcare'], 'Enterprise', 'End-to-end AI/ML platform with data pipelines, model training, and deployment infrastructure', AI_SECTIONS, [{ role: 'AI/ML Engineer', count: 3, geo: 'india' }, { role: 'Data Architect', count: 1, geo: 'us' }, { role: 'DevOps Engineer', count: 1, geo: 'india' }, { role: 'Program Manager', count: 1, geo: 'us' }], ['ML platform architecture', 'Data pipeline implementation', 'Model serving infrastructure', 'MLOps automation', 'Documentation & training'], ['Data quality issues', 'Model performance', 'Scalability challenges', 'Regulatory compliance'], '6-12 months', '$500K-$2M', ['AI', 'ML', 'Platform', 'Data Engineering'], 'Enterprise AI/ML platform implementation with focus on scalability and governance'),
  makeTemplate('ai-02', 'Generative AI Application', 'AI & Data Engineering', 'Time & Material', ['Technology', 'Professional Services', 'Retail'], 'Complex', 'Custom GenAI application leveraging LLMs for specific business use cases', AI_SECTIONS, [{ role: 'AI/ML Engineer', count: 2, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'Technical Architect', count: 1, geo: 'us' }], ['GenAI application', 'RAG pipeline', 'Prompt engineering framework', 'Evaluation suite', 'User documentation'], ['LLM hallucination risks', 'Data privacy concerns', 'Cost management', 'User adoption'], '3-6 months', '$200K-$800K', ['GenAI', 'LLM', 'RAG', 'NLP'], 'Generative AI application with retrieval-augmented generation and enterprise guardrails'),
  makeTemplate('ai-03', 'Data Lake / Lakehouse', 'AI & Data Engineering', 'Fixed Price', ['Financial Services', 'Healthcare', 'Retail', 'Manufacturing'], 'Enterprise', 'Modern data lakehouse architecture on cloud with unified analytics', AI_SECTIONS, [{ role: 'Data Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'DevOps Engineer', count: 1, geo: 'india' }], ['Data lakehouse architecture', 'ETL/ELT pipelines', 'Data governance framework', 'Self-service analytics layer', 'Performance optimization'], ['Data migration complexity', 'Schema evolution', 'Query performance', 'Cost overruns'], '4-9 months', '$300K-$1.5M', ['Data Lake', 'Lakehouse', 'Analytics', 'Databricks', 'Snowflake'], 'Modern data lakehouse with unified analytics and governance'),
  makeTemplate('ai-04', 'Computer Vision Solution', 'AI & Data Engineering', 'Fixed Price', ['Manufacturing', 'Healthcare', 'Retail'], 'Complex', 'Computer vision system for quality inspection, monitoring, or visual search', AI_SECTIONS, [{ role: 'AI/ML Engineer', count: 2, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 1, geo: 'india' }, { role: 'QA Engineer', count: 1, geo: 'india' }], ['CV model trained on client data', 'Inference pipeline', 'Integration with existing systems', 'Monitoring dashboard', 'Accuracy benchmarks'], ['Training data quality', 'Edge deployment challenges', 'Accuracy requirements', 'Lighting/environment variables'], '3-6 months', '$150K-$600K', ['Computer Vision', 'Deep Learning', 'Image Processing'], 'Computer vision solution for visual inspection and automated analysis'),
  makeTemplate('ai-05', 'NLP/Conversational AI', 'AI & Data Engineering', 'Time & Material', ['Financial Services', 'Healthcare', 'Professional Services'], 'Complex', 'Conversational AI chatbot or NLP processing pipeline', AI_SECTIONS, [{ role: 'AI/ML Engineer', count: 2, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 1, geo: 'india' }, { role: 'UX Designer', count: 1, geo: 'india' }], ['Conversational AI bot', 'Intent classification model', 'Entity extraction pipeline', 'Conversation management', 'Analytics dashboard'], ['Intent accuracy', 'Multi-language support', 'Context handling', 'Integration complexity'], '3-6 months', '$200K-$700K', ['NLP', 'Chatbot', 'Conversational AI'], 'NLP-powered conversational AI with enterprise integration'),
  makeTemplate('ai-06', 'Data Analytics & BI Platform', 'AI & Data Engineering', 'Fixed Price', ['All'], 'Standard', 'Business intelligence platform with dashboards, reporting, and self-service analytics', [], [{ role: 'Data Architect', count: 1, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['BI platform setup', 'Executive dashboards', 'Self-service analytics', 'Data dictionary', 'Training materials'], ['Data quality', 'User adoption', 'Performance tuning'], '2-4 months', '$100K-$400K', ['BI', 'Analytics', 'Dashboards', 'Power BI', 'Tableau'], 'Enterprise BI and analytics platform with self-service capabilities'),
  makeTemplate('ai-07', 'Real-Time Streaming Analytics', 'AI & Data Engineering', 'Time & Material', ['Financial Services', 'Telecom', 'Technology'], 'Enterprise', 'Real-time data streaming and analytics with event-driven architecture', AI_SECTIONS, [{ role: 'Data Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'DevOps Engineer', count: 1, geo: 'india' }], ['Streaming architecture', 'Real-time dashboards', 'Alert engine', 'Data retention policies', 'Performance benchmarks'], ['Throughput requirements', 'Latency guarantees', 'Data ordering', 'Exactly-once processing'], '4-8 months', '$400K-$1.2M', ['Kafka', 'Streaming', 'Real-time', 'Flink', 'Spark Streaming'], 'Real-time streaming analytics with event-driven architecture'),
  makeTemplate('ai-08', 'Data Governance & Quality', 'AI & Data Engineering', 'Consulting', ['Financial Services', 'Healthcare', 'Government'], 'Complex', 'Data governance framework, quality monitoring, and compliance automation', AI_SECTIONS, [{ role: 'Data Architect', count: 1, geo: 'us' }, { role: 'Business Analyst', count: 2, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 1, geo: 'india' }], ['Governance framework', 'Data catalog', 'Quality rules engine', 'Compliance dashboards', 'Policy documentation'], ['Organizational resistance', 'Legacy system integration', 'Ongoing maintenance'], '3-6 months', '$200K-$600K', ['Data Governance', 'Data Quality', 'Compliance', 'Master Data'], 'Data governance framework with automated quality monitoring and compliance'),
  makeTemplate('ai-09', 'Recommendation Engine', 'AI & Data Engineering', 'Fixed Price', ['Retail', 'Technology', 'Hospitality'], 'Standard', 'Personalized recommendation system for products, content, or services', AI_SECTIONS, [{ role: 'AI/ML Engineer', count: 2, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 1, geo: 'india' }], ['Recommendation model', 'A/B testing framework', 'Real-time serving API', 'Performance metrics', 'Business impact analysis'], ['Cold start problem', 'Scalability', 'Bias in recommendations'], '2-4 months', '$100K-$400K', ['Recommendation', 'Personalization', 'ML'], 'Personalized recommendation engine with A/B testing and real-time serving'),
  makeTemplate('ai-10', 'Predictive Analytics', 'AI & Data Engineering', 'Time & Material', ['Financial Services', 'Manufacturing', 'Healthcare'], 'Complex', 'Predictive models for forecasting, risk scoring, or demand planning', AI_SECTIONS, [{ role: 'AI/ML Engineer', count: 2, geo: 'india' }, { role: 'Business Analyst', count: 1, geo: 'india' }, { role: 'Data Architect', count: 1, geo: 'india' }], ['Predictive models', 'Feature engineering pipeline', 'Model monitoring', 'Business dashboards', 'Decision support tools'], ['Data availability', 'Model interpretability', 'Regulatory requirements'], '3-6 months', '$200K-$700K', ['Prediction', 'Forecasting', 'Risk Scoring'], 'Predictive analytics for business forecasting and decision support'),
  makeTemplate('ai-11', 'Data Migration & Modernization', 'AI & Data Engineering', 'Fixed Price', ['All'], 'Complex', 'Legacy data platform migration to modern cloud-native architecture', [], [{ role: 'Data Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'QA Engineer', count: 1, geo: 'india' }], ['Migration strategy document', 'Data mapping specifications', 'Migrated data platform', 'Validation reports', 'Runbooks'], ['Data loss risk', 'Downtime windows', 'Schema incompatibilities', 'Performance regression'], '3-8 months', '$200K-$800K', ['Migration', 'Modernization', 'Legacy'], 'Data platform migration from legacy to cloud-native architecture'),
  makeTemplate('ai-12', 'IoT Analytics Platform', 'AI & Data Engineering', 'Fixed Price', ['Manufacturing', 'Energy', 'Healthcare'], 'Enterprise', 'IoT data ingestion, processing, and analytics platform', AI_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'DevOps Engineer', count: 1, geo: 'india' }], ['IoT data platform', 'Edge processing framework', 'Real-time dashboards', 'Predictive maintenance models', 'Alert system'], ['Device connectivity', 'Data volume', 'Edge computing constraints', 'Security'], '6-12 months', '$500K-$1.5M', ['IoT', 'Edge', 'Sensors', 'Real-time'], 'IoT analytics platform with edge processing and predictive maintenance'),
  makeTemplate('ai-13', 'Knowledge Graph & Semantic Search', 'AI & Data Engineering', 'Time & Material', ['Technology', 'Healthcare', 'Financial Services'], 'Complex', 'Knowledge graph construction with semantic search and entity resolution', AI_SECTIONS, [{ role: 'AI/ML Engineer', count: 2, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 1, geo: 'india' }], ['Knowledge graph', 'Entity resolution pipeline', 'Semantic search API', 'Graph visualization', 'Data enrichment framework'], ['Entity disambiguation', 'Graph scalability', 'Query performance'], '3-6 months', '$200K-$600K', ['Knowledge Graph', 'Graph DB', 'Semantic Search', 'Neo4j'], 'Knowledge graph with semantic search and intelligent entity resolution'),
  makeTemplate('ai-14', 'MLOps & Model Management', 'AI & Data Engineering', 'Fixed Price', ['Technology', 'Financial Services'], 'Complex', 'MLOps platform for model lifecycle management, CI/CD for ML, and monitoring', AI_SECTIONS, [{ role: 'DevOps Engineer', count: 2, geo: 'india' }, { role: 'AI/ML Engineer', count: 1, geo: 'india' }, { role: 'Technical Architect', count: 1, geo: 'us' }], ['MLOps platform', 'CI/CD pipeline for ML', 'Model registry', 'A/B testing framework', 'Drift monitoring'], ['Tool fragmentation', 'Team skill gaps', 'Reproducibility'], '3-6 months', '$200K-$600K', ['MLOps', 'CI/CD', 'Model Management', 'Kubeflow'], 'MLOps platform for end-to-end ML lifecycle management'),
  makeTemplate('ai-15', 'Document Intelligence', 'AI & Data Engineering', 'Fixed Price', ['Financial Services', 'Healthcare', 'Government'], 'Standard', 'Intelligent document processing with OCR, extraction, and classification', AI_SECTIONS, [{ role: 'AI/ML Engineer', count: 2, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 1, geo: 'india' }], ['Document processing pipeline', 'OCR/extraction models', 'Classification system', 'Validation UI', 'API integration'], ['Document variety', 'Accuracy requirements', 'Volume processing'], '2-4 months', '$100K-$400K', ['OCR', 'Document AI', 'IDP', 'Extraction'], 'Intelligent document processing for automated extraction and classification'),

  // ═══════════════════════════════════════════
  // CLOUD & INFRASTRUCTURE (15 templates)
  // ═══════════════════════════════════════════
  makeTemplate('cloud-01', 'Cloud Migration (Lift & Shift)', 'Cloud & Infrastructure', 'Fixed Price', ['All'], 'Complex', 'Large-scale migration of on-premises workloads to cloud', CLOUD_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'DevOps Engineer', count: 3, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'Program Manager', count: 1, geo: 'us' }], ['Migration assessment', 'Landing zone', 'Migrated workloads', 'Cutover documentation', 'Operational runbooks'], ['Downtime constraints', 'Application dependencies', 'Data transfer time', 'Cost overruns'], '6-12 months', '$500K-$2M', ['AWS', 'Azure', 'GCP', 'Migration', 'Lift & Shift'], 'Large-scale cloud migration with wave planning and zero-downtime cutover'),
  makeTemplate('cloud-02', 'Cloud-Native Application Platform', 'Cloud & Infrastructure', 'Fixed Price', ['Technology', 'Financial Services', 'Retail'], 'Enterprise', 'Kubernetes-based cloud-native platform with CI/CD, monitoring, and self-service', CLOUD_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'DevOps Engineer', count: 3, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }], ['Kubernetes platform', 'CI/CD pipelines', 'Monitoring stack', 'Developer portal', 'Security policies'], ['Complexity', 'Skill gaps', 'Multi-tenancy', 'Cost management'], '4-8 months', '$400K-$1.5M', ['Kubernetes', 'Docker', 'Cloud-Native', 'Platform Engineering'], 'Cloud-native application platform with Kubernetes and developer self-service'),
  makeTemplate('cloud-03', 'Infrastructure as Code', 'Cloud & Infrastructure', 'Time & Material', ['All'], 'Standard', 'IaC implementation with Terraform/Pulumi for repeatable infrastructure', CLOUD_SECTIONS, [{ role: 'DevOps Engineer', count: 2, geo: 'india' }, { role: 'Technical Architect', count: 1, geo: 'india' }], ['IaC codebase', 'Module library', 'Pipeline automation', 'Documentation', 'Training'], ['State management', 'Drift detection', 'Multi-environment'], '2-4 months', '$100K-$300K', ['Terraform', 'IaC', 'Infrastructure', 'Automation'], 'Infrastructure as Code with Terraform for repeatable cloud provisioning'),
  makeTemplate('cloud-04', 'Disaster Recovery & HA', 'Cloud & Infrastructure', 'Fixed Price', ['Financial Services', 'Healthcare', 'Government'], 'Enterprise', 'Multi-region DR strategy with automated failover and RPO/RTO guarantees', CLOUD_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'DevOps Engineer', count: 2, geo: 'india' }], ['DR architecture', 'Failover automation', 'Runbooks', 'DR testing framework', 'RTO/RPO documentation'], ['RTO/RPO requirements', 'Cost of multi-region', 'Data consistency'], '3-6 months', '$200K-$800K', ['DR', 'HA', 'Multi-Region', 'Failover'], 'Disaster recovery with automated multi-region failover'),
  makeTemplate('cloud-05', 'Cloud Cost Optimization', 'Cloud & Infrastructure', 'Consulting', ['All'], 'Standard', 'Cloud spend analysis, right-sizing, and FinOps implementation', [], [{ role: 'Technical Architect', count: 1, geo: 'india' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['Cost analysis report', 'Optimization recommendations', 'FinOps dashboards', 'Reserved instance strategy', 'Governance policies'], ['Organizational buy-in', 'Workload variability'], '1-3 months', '$50K-$200K', ['FinOps', 'Cost Optimization', 'Right-Sizing'], 'Cloud cost optimization with FinOps practices and automated governance'),
  makeTemplate('cloud-06', 'Multi-Cloud Strategy', 'Cloud & Infrastructure', 'Consulting', ['Enterprise', 'Financial Services'], 'Enterprise', 'Multi-cloud architecture strategy across AWS, Azure, and GCP', CLOUD_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'DevOps Engineer', count: 2, geo: 'india' }], ['Multi-cloud strategy', 'Architecture patterns', 'Networking design', 'Identity federation', 'Governance framework'], ['Complexity', 'Skill requirements', 'Vendor lock-in', 'Cost management'], '3-6 months', '$200K-$600K', ['Multi-Cloud', 'AWS', 'Azure', 'GCP', 'Strategy'], 'Multi-cloud architecture strategy with unified governance'),
  makeTemplate('cloud-07', 'Serverless Architecture', 'Cloud & Infrastructure', 'Time & Material', ['Technology', 'Retail'], 'Standard', 'Event-driven serverless architecture with API Gateway, Lambda, and managed services', CLOUD_SECTIONS, [{ role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'DevOps Engineer', count: 1, geo: 'india' }], ['Serverless architecture', 'API Gateway setup', 'Event-driven pipelines', 'Monitoring & alerting', 'Cost analysis'], ['Cold starts', 'Vendor lock-in', 'Debugging complexity'], '2-4 months', '$100K-$400K', ['Serverless', 'Lambda', 'API Gateway', 'Event-Driven'], 'Serverless architecture for cost-efficient, auto-scaling applications'),
  makeTemplate('cloud-08', 'Container Platform Migration', 'Cloud & Infrastructure', 'Fixed Price', ['Technology', 'Financial Services'], 'Complex', 'Containerize and migrate monolithic applications to Kubernetes', CLOUD_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'DevOps Engineer', count: 2, geo: 'india' }], ['Containerization assessment', 'Docker images', 'Kubernetes manifests', 'CI/CD pipelines', 'Migration runbooks'], ['Application decomposition', 'State management', 'Networking complexity'], '4-8 months', '$300K-$1M', ['Containers', 'Docker', 'Kubernetes', 'Microservices'], 'Container-based modernization from monolith to microservices'),

  // ═══════════════════════════════════════════
  // APPLICATION DEVELOPMENT (15 templates)
  // ═══════════════════════════════════════════
  makeTemplate('app-01', 'Custom Web Application', 'Application Development', 'Time & Material', ['All'], 'Standard', 'Full-stack web application with modern frameworks', [], [{ role: 'Technical Architect', count: 1, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'UX Designer', count: 1, geo: 'india' }, { role: 'QA Engineer', count: 1, geo: 'india' }], ['Web application', 'API documentation', 'Test suite', 'Deployment guide', 'User documentation'], ['Scope creep', 'UX complexity', 'Integration challenges', 'Performance'], '3-9 months', '$150K-$600K', ['React', 'Next.js', 'Node.js', 'Full-Stack'], 'Custom web application with React/Next.js frontend and Node.js backend'),
  makeTemplate('app-02', 'Mobile Application (Cross-Platform)', 'Application Development', 'Fixed Price', ['All'], 'Complex', 'Cross-platform mobile app for iOS and Android', [], [{ role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'UX Designer', count: 1, geo: 'india' }, { role: 'QA Engineer', count: 2, geo: 'india' }], ['iOS & Android apps', 'Backend APIs', 'Push notification system', 'Analytics integration', 'App store submissions'], ['Platform differences', 'App store guidelines', 'Device fragmentation', 'Performance'], '4-8 months', '$200K-$800K', ['React Native', 'Flutter', 'Mobile', 'iOS', 'Android'], 'Cross-platform mobile application with native performance'),
  makeTemplate('app-03', 'API Platform & Gateway', 'Application Development', 'Fixed Price', ['Technology', 'Financial Services', 'Healthcare'], 'Complex', 'Enterprise API platform with gateway, developer portal, and monetization', [], [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'DevOps Engineer', count: 1, geo: 'india' }], ['API gateway', 'Developer portal', 'API documentation', 'Rate limiting & security', 'Analytics'], ['API versioning', 'Backward compatibility', 'Security', 'Performance at scale'], '3-6 months', '$200K-$600K', ['API', 'Gateway', 'REST', 'GraphQL', 'Developer Portal'], 'Enterprise API platform with gateway, security, and developer self-service'),
  makeTemplate('app-04', 'Legacy Application Modernization', 'Application Development', 'Fixed Price', ['Financial Services', 'Manufacturing', 'Government'], 'Enterprise', 'Modernize legacy applications using strangler fig pattern', [], [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 4, geo: 'india' }, { role: 'QA Engineer', count: 2, geo: 'india' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['Modernization assessment', 'Refactored application', 'Data migration', 'Integration layer', 'Documentation'], ['Legacy complexity', 'Business logic preservation', 'Data migration risks', 'Change management'], '6-18 months', '$500K-$3M', ['Legacy', 'Modernization', 'Strangler Fig', 'Microservices'], 'Legacy modernization using strangler fig pattern with zero business disruption'),
  makeTemplate('app-05', 'E-Commerce Platform', 'Application Development', 'Fixed Price', ['Retail', 'Manufacturing'], 'Complex', 'Custom e-commerce platform with product catalog, cart, payments, and order management', [], [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'UX Designer', count: 1, geo: 'india' }, { role: 'QA Engineer', count: 2, geo: 'india' }], ['E-commerce platform', 'Product catalog', 'Payment integration', 'Order management', 'Analytics'], ['Payment compliance', 'Scalability during peaks', 'Security', 'SEO'], '4-8 months', '$300K-$1M', ['E-Commerce', 'Payments', 'Shopify', 'Custom'], 'Custom e-commerce with product catalog, payments, and order management'),
  makeTemplate('app-06', 'Customer Portal / Self-Service', 'Application Development', 'Time & Material', ['All'], 'Standard', 'Customer-facing portal with self-service capabilities, ticketing, and dashboards', [], [{ role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'UX Designer', count: 1, geo: 'india' }, { role: 'QA Engineer', count: 1, geo: 'india' }], ['Customer portal', 'Self-service features', 'Ticketing integration', 'Dashboard', 'SSO integration'], ['User experience', 'Integration complexity', 'Performance'], '3-6 months', '$150K-$500K', ['Portal', 'Self-Service', 'Customer Experience'], 'Customer portal with self-service, ticketing, and real-time dashboards'),
  makeTemplate('app-07', 'Microservices Architecture', 'Application Development', 'Fixed Price', ['Technology', 'Financial Services'], 'Enterprise', 'Decompose monolith into microservices with event-driven communication', [], [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 4, geo: 'india' }, { role: 'DevOps Engineer', count: 2, geo: 'india' }], ['Microservices architecture', 'Service mesh', 'Event bus', 'API contracts', 'Deployment automation'], ['Service boundaries', 'Data consistency', 'Distributed tracing', 'Team coordination'], '6-12 months', '$500K-$2M', ['Microservices', 'Event-Driven', 'Service Mesh', 'Domain-Driven'], 'Microservices transformation with event-driven architecture and service mesh'),

  // ═══════════════════════════════════════════
  // ENTERPRISE ARCHITECTURE (10 templates)
  // ═══════════════════════════════════════════
  makeTemplate('ea-01', 'Enterprise Architecture Assessment', 'Enterprise Architecture', 'Consulting', ['All'], 'Enterprise', 'Comprehensive EA assessment with target state architecture and roadmap', [], [{ role: 'Technical Architect', count: 2, geo: 'us' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['Current state assessment', 'Target state architecture', 'Gap analysis', 'Transformation roadmap', 'Governance framework'], ['Stakeholder alignment', 'Legacy constraints', 'Budget constraints'], '2-4 months', '$200K-$500K', ['Enterprise Architecture', 'TOGAF', 'Roadmap'], 'Enterprise architecture assessment with TOGAF-aligned transformation roadmap'),
  makeTemplate('ea-02', 'Integration Architecture (iPaaS)', 'Enterprise Architecture', 'Fixed Price', ['All'], 'Complex', 'Enterprise integration platform with API management, ESB, and iPaaS', [], [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }], ['Integration architecture', 'iPaaS implementation', 'API catalog', 'Data mapping', 'Monitoring'], ['Integration complexity', 'Data format inconsistencies', 'Performance'], '4-8 months', '$300K-$1M', ['Integration', 'iPaaS', 'ESB', 'MuleSoft', 'Boomi'], 'Enterprise integration platform connecting disparate systems'),
  makeTemplate('ea-03', 'Digital Twin Architecture', 'Enterprise Architecture', 'Fixed Price', ['Manufacturing', 'Energy', 'Healthcare'], 'Enterprise', 'Digital twin platform for physical asset simulation and monitoring', AI_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'AI/ML Engineer', count: 2, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }], ['Digital twin platform', 'Simulation models', 'Real-time monitoring', 'Predictive analytics', '3D visualization'], ['Data accuracy', 'Model fidelity', 'Real-time processing', 'Scale'], '6-12 months', '$500K-$2M', ['Digital Twin', 'IoT', 'Simulation', '3D'], 'Digital twin platform for real-time asset monitoring and predictive simulation'),
  makeTemplate('ea-04', 'Event-Driven Architecture', 'Enterprise Architecture', 'Time & Material', ['Technology', 'Financial Services', 'Retail'], 'Complex', 'Event-driven architecture with event sourcing and CQRS patterns', [], [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }], ['Event architecture', 'Event store', 'CQRS implementation', 'Saga orchestration', 'Monitoring'], ['Event ordering', 'Idempotency', 'Debugging complexity', 'Team learning curve'], '4-8 months', '$300K-$900K', ['Event Sourcing', 'CQRS', 'Kafka', 'Event-Driven'], 'Event-driven architecture with CQRS and event sourcing patterns'),
  makeTemplate('ea-05', 'Platform Engineering', 'Enterprise Architecture', 'Managed Service', ['Technology', 'Financial Services'], 'Enterprise', 'Internal developer platform with golden paths, self-service, and guardrails', [], [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'DevOps Engineer', count: 3, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }], ['Developer platform', 'Service catalog', 'Golden path templates', 'Self-service portal', 'Guardrails'], ['Developer adoption', 'Maintenance burden', 'Platform complexity'], '6-12 months', '$400K-$1.5M', ['Platform Engineering', 'Developer Experience', 'IDP', 'Backstage'], 'Internal developer platform with self-service and automated guardrails'),

  // ═══════════════════════════════════════════
  // ERP & BUSINESS APPLICATIONS (10 templates)
  // ═══════════════════════════════════════════
  makeTemplate('erp-01', 'SAP S/4HANA Migration', 'ERP & Business Applications', 'Fixed Price', ['Manufacturing', 'Retail', 'Energy'], 'Enterprise', 'SAP ECC to S/4HANA migration with custom code remediation', ERP_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 4, geo: 'india' }, { role: 'Business Analyst', count: 2, geo: 'india' }, { role: 'Program Manager', count: 1, geo: 'us' }], ['Migration assessment', 'Custom code remediation', 'Data migration', 'Testing', 'Go-live support'], ['Custom code volume', 'Data complexity', 'Business disruption', 'Testing coverage'], '12-24 months', '$1M-$5M', ['SAP', 'S/4HANA', 'Migration', 'ERP'], 'SAP S/4HANA migration with comprehensive custom code remediation'),
  makeTemplate('erp-02', 'Salesforce Implementation', 'ERP & Business Applications', 'Fixed Price', ['All'], 'Complex', 'Salesforce CRM implementation with custom objects, workflows, and integrations', ERP_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['Salesforce configuration', 'Custom development', 'Data migration', 'Integration setup', 'Training materials'], ['Data quality', 'User adoption', 'Integration complexity', 'Customization limits'], '3-9 months', '$200K-$800K', ['Salesforce', 'CRM', 'Apex', 'Lightning'], 'Salesforce CRM implementation with custom development and integration'),
  makeTemplate('erp-03', 'ServiceNow ITSM', 'ERP & Business Applications', 'Fixed Price', ['All'], 'Complex', 'ServiceNow ITSM implementation with ITIL processes and automation', ERP_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['ServiceNow configuration', 'ITIL process setup', 'Workflow automation', 'CMDB population', 'Training'], ['Process standardization', 'CMDB accuracy', 'Integration with existing tools'], '3-6 months', '$200K-$600K', ['ServiceNow', 'ITSM', 'ITIL', 'Automation'], 'ServiceNow ITSM with ITIL-aligned processes and intelligent automation'),
  makeTemplate('erp-04', 'Workday HCM Implementation', 'ERP & Business Applications', 'Fixed Price', ['All'], 'Enterprise', 'Workday HCM deployment with core HR, payroll, and talent management', ERP_SECTIONS, [{ role: 'Business Analyst', count: 2, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'Program Manager', count: 1, geo: 'us' }], ['Workday configuration', 'Data migration', 'Integration design', 'UAT', 'Change management'], ['Data complexity', 'Payroll accuracy', 'Regulatory compliance', 'Global rollout'], '6-12 months', '$500K-$2M', ['Workday', 'HCM', 'HR', 'Payroll'], 'Workday HCM implementation with global payroll and talent management'),
  makeTemplate('erp-05', 'Low-Code/No-Code Platform', 'ERP & Business Applications', 'Time & Material', ['All'], 'Standard', 'Business application development using low-code platforms (Power Platform, OutSystems, Mendix)', [], [{ role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['Low-code applications', 'Integration connectors', 'Governance framework', 'Citizen developer training', 'Documentation'], ['Platform limitations', 'Scalability', 'Vendor lock-in'], '2-4 months', '$80K-$300K', ['Low-Code', 'Power Platform', 'OutSystems', 'Mendix'], 'Low-code application development for rapid business automation'),

  // ═══════════════════════════════════════════
  // MANAGED SERVICES (10 templates)
  // ═══════════════════════════════════════════
  makeTemplate('ms-01', 'Application Managed Services', 'Managed Services', 'Managed Service', ['All'], 'Complex', '24/7 application support, monitoring, and continuous improvement', MANAGED_SECTIONS, [{ role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'DevOps Engineer', count: 2, geo: 'india' }, { role: 'Program Manager', count: 1, geo: 'us' }], ['Support model', 'Monitoring setup', 'Runbooks', 'Monthly reports', 'Continuous improvement plan'], ['Knowledge transfer', 'SLA commitments', 'Tool standardization'], '12-36 months', '$500K-$3M/year', ['Managed Services', 'AMS', 'Support', '24/7'], 'Application managed services with 24/7 support and continuous improvement'),
  makeTemplate('ms-02', 'Cloud Managed Services', 'Managed Services', 'Managed Service', ['All'], 'Enterprise', 'Cloud infrastructure management, optimization, and security', MANAGED_SECTIONS, [{ role: 'DevOps Engineer', count: 3, geo: 'india' }, { role: 'Technical Architect', count: 1, geo: 'us' }], ['Cloud operations model', 'Monitoring & alerting', 'Security posture management', 'Cost optimization', 'Compliance reporting'], ['Multi-cloud complexity', 'Security incidents', 'Cost control'], '12-36 months', '$300K-$2M/year', ['Cloud Ops', 'Managed Cloud', 'FinOps'], 'Cloud managed services with FinOps and security posture management'),
  makeTemplate('ms-03', 'NOC/SOC Operations', 'Managed Services', 'Managed Service', ['Financial Services', 'Healthcare', 'Government'], 'Enterprise', 'Network and Security Operations Center with 24/7 monitoring', [...MANAGED_SECTIONS, ...SECURITY_SECTIONS], [{ role: 'DevOps Engineer', count: 4, geo: 'india' }, { role: 'Technical Architect', count: 1, geo: 'us' }], ['NOC/SOC setup', 'Monitoring tools deployment', 'Incident response procedures', 'Threat hunting playbooks', 'Compliance dashboards'], ['Alert fatigue', 'False positives', 'Skill retention', 'Tool integration'], '12+ months', '$500K-$2M/year', ['NOC', 'SOC', 'SIEM', 'Monitoring', '24/7'], 'NOC/SOC operations with threat hunting and automated incident response'),
  makeTemplate('ms-04', 'DevOps as a Service', 'Managed Services', 'Managed Service', ['Technology', 'Financial Services'], 'Complex', 'Managed DevOps with CI/CD, infrastructure automation, and SRE practices', MANAGED_SECTIONS, [{ role: 'DevOps Engineer', count: 3, geo: 'india' }, { role: 'Technical Architect', count: 1, geo: 'india' }], ['DevOps toolchain', 'CI/CD pipelines', 'SRE practices', 'Automation library', 'SLA dashboards'], ['Tool sprawl', 'Cultural change', 'Reliability targets'], '12+ months', '$300K-$1M/year', ['DevOps', 'SRE', 'CI/CD', 'Automation'], 'Managed DevOps with SRE practices and infrastructure automation'),
  makeTemplate('ms-05', 'Data Operations (DataOps)', 'Managed Services', 'Managed Service', ['Financial Services', 'Healthcare', 'Retail'], 'Complex', 'Managed data operations including pipeline management, quality, and governance', MANAGED_SECTIONS, [{ role: 'Data Architect', count: 1, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }], ['DataOps platform', 'Pipeline monitoring', 'Data quality dashboards', 'Governance automation', 'SLA reports'], ['Data volume growth', 'Pipeline failures', 'Compliance changes'], '12+ months', '$200K-$800K/year', ['DataOps', 'Data Pipeline', 'Data Quality'], 'Managed DataOps with automated quality monitoring and governance'),

  // ═══════════════════════════════════════════
  // QA & TESTING (10 templates)
  // ═══════════════════════════════════════════
  makeTemplate('qa-01', 'Test Automation Framework', 'QA & Testing', 'Fixed Price', ['All'], 'Standard', 'End-to-end test automation framework with CI/CD integration', [], [{ role: 'QA Engineer', count: 3, geo: 'india' }, { role: 'Technical Architect', count: 1, geo: 'india' }], ['Test framework', 'Automation scripts', 'CI/CD integration', 'Test reporting', 'Training'], ['Application complexity', 'Test data management', 'Flaky tests'], '2-4 months', '$100K-$300K', ['Test Automation', 'Selenium', 'Cypress', 'CI/CD'], 'Test automation framework with CI/CD integration and reporting'),
  makeTemplate('qa-02', 'Performance & Load Testing', 'QA & Testing', 'Time & Material', ['Technology', 'Financial Services', 'Retail'], 'Complex', 'Comprehensive performance testing with load simulation and bottleneck analysis', [], [{ role: 'QA Engineer', count: 2, geo: 'india' }, { role: 'DevOps Engineer', count: 1, geo: 'india' }], ['Performance test strategy', 'Load test scripts', 'Bottleneck analysis', 'Optimization recommendations', 'Benchmark report'], ['Environment parity', 'Test data realism', 'Infrastructure costs'], '1-3 months', '$80K-$250K', ['Performance', 'Load Testing', 'JMeter', 'k6', 'Gatling'], 'Performance and load testing with bottleneck analysis and optimization'),
  makeTemplate('qa-03', 'QA Center of Excellence', 'QA & Testing', 'Managed Service', ['Enterprise'], 'Enterprise', 'Establish a QA CoE with standards, tools, training, and governance', [], [{ role: 'QA Engineer', count: 4, geo: 'india' }, { role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Program Manager', count: 1, geo: 'us' }], ['QA CoE charter', 'Testing standards', 'Tool landscape', 'Training program', 'Metrics dashboard'], ['Organizational buy-in', 'Standardization across teams', 'Tooling consolidation'], '6-12 months', '$300K-$800K', ['QA CoE', 'Testing Standards', 'Governance'], 'QA Center of Excellence with standards, governance, and continuous improvement'),
  makeTemplate('qa-04', 'Security Testing (DAST/SAST)', 'QA & Testing', 'Time & Material', ['Financial Services', 'Healthcare', 'Government'], 'Complex', 'Application security testing with SAST, DAST, and penetration testing', SECURITY_SECTIONS, [{ role: 'QA Engineer', count: 2, geo: 'india' }, { role: 'DevOps Engineer', count: 1, geo: 'india' }], ['SAST/DAST reports', 'Vulnerability assessment', 'Penetration test report', 'Remediation guide', 'Security pipeline'], ['False positive management', 'Remediation prioritization', 'Continuous scanning'], '1-3 months', '$80K-$250K', ['Security Testing', 'SAST', 'DAST', 'Pen Testing'], 'Application security testing with SAST, DAST, and pen testing'),
  makeTemplate('qa-05', 'AI/ML Model Testing', 'QA & Testing', 'Time & Material', ['Technology', 'Financial Services', 'Healthcare'], 'Complex', 'ML model testing including fairness, robustness, and performance validation', AI_SECTIONS, [{ role: 'AI/ML Engineer', count: 1, geo: 'india' }, { role: 'QA Engineer', count: 2, geo: 'india' }], ['Model test framework', 'Fairness assessment', 'Robustness testing', 'Performance benchmarks', 'Monitoring setup'], ['Test data quality', 'Bias detection', 'Adversarial scenarios'], '1-3 months', '$80K-$250K', ['AI Testing', 'ML Validation', 'Fairness', 'Robustness'], 'AI/ML model testing for fairness, robustness, and production readiness'),

  // ═══════════════════════════════════════════
  // DEVSECOPS (8 templates)
  // ═══════════════════════════════════════════
  makeTemplate('devops-01', 'CI/CD Pipeline Implementation', 'DevSecOps', 'Fixed Price', ['All'], 'Standard', 'Modern CI/CD pipeline with automated testing, security scanning, and deployment', [], [{ role: 'DevOps Engineer', count: 2, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 1, geo: 'india' }], ['CI/CD pipelines', 'Build automation', 'Security scanning', 'Deployment strategies', 'Documentation'], ['Pipeline complexity', 'Environment management', 'Secrets management'], '2-3 months', '$80K-$200K', ['CI/CD', 'Jenkins', 'GitHub Actions', 'GitLab CI'], 'Modern CI/CD with automated testing, scanning, and blue-green deployment'),
  makeTemplate('devops-02', 'Site Reliability Engineering', 'DevSecOps', 'Managed Service', ['Technology', 'Financial Services'], 'Enterprise', 'SRE implementation with SLOs, error budgets, and incident management', MANAGED_SECTIONS, [{ role: 'DevOps Engineer', count: 3, geo: 'india' }, { role: 'Technical Architect', count: 1, geo: 'us' }], ['SRE practice', 'SLO framework', 'Error budgets', 'Incident management', 'Postmortem process'], ['Cultural change', 'Reliability targets', 'On-call burden'], '6+ months', '$300K-$800K', ['SRE', 'Reliability', 'SLO', 'Incident Management'], 'SRE implementation with SLOs, error budgets, and blameless postmortems'),
  makeTemplate('devops-03', 'Observability Platform', 'DevSecOps', 'Fixed Price', ['Technology', 'Financial Services', 'Retail'], 'Complex', 'Full observability stack with metrics, logs, traces, and alerting', [], [{ role: 'DevOps Engineer', count: 2, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 1, geo: 'india' }], ['Observability platform', 'Dashboard library', 'Alert rules', 'Runbooks', 'Training'], ['Data volume', 'Alert fatigue', 'Tool consolidation'], '2-4 months', '$100K-$400K', ['Observability', 'Monitoring', 'Logging', 'Tracing', 'Grafana', 'Datadog'], 'Full-stack observability with metrics, logs, distributed tracing, and intelligent alerting'),

  // ═══════════════════════════════════════════
  // DIGITAL TRANSFORMATION (10 templates)
  // ═══════════════════════════════════════════
  makeTemplate('dt-01', 'Digital Transformation Strategy', 'Digital Transformation', 'Consulting', ['All'], 'Enterprise', 'Comprehensive digital transformation strategy with technology roadmap', [], [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Business Analyst', count: 2, geo: 'india' }, { role: 'Program Manager', count: 1, geo: 'us' }], ['Strategy document', 'Technology roadmap', 'Business case', 'Governance framework', 'KPI dashboard'], ['Executive alignment', 'Budget constraints', 'Change resistance', 'Skill gaps'], '2-4 months', '$200K-$500K', ['Digital Transformation', 'Strategy', 'Roadmap'], 'Digital transformation strategy with technology roadmap and business case'),
  makeTemplate('dt-02', 'Process Automation (RPA + AI)', 'Digital Transformation', 'Fixed Price', ['Financial Services', 'Healthcare', 'Manufacturing'], 'Complex', 'Intelligent process automation combining RPA with AI/ML', AI_SECTIONS, [{ role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'AI/ML Engineer', count: 1, geo: 'india' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['Process assessment', 'RPA bots', 'AI models', 'Orchestration', 'ROI dashboard'], ['Process variability', 'Exception handling', 'Maintenance overhead', 'Scale'], '3-6 months', '$200K-$600K', ['RPA', 'Automation', 'UiPath', 'IPA'], 'Intelligent process automation combining RPA with AI for end-to-end automation'),
  makeTemplate('dt-03', 'Customer Experience Platform', 'Digital Transformation', 'Fixed Price', ['Retail', 'Financial Services', 'Hospitality'], 'Enterprise', 'Omnichannel customer experience platform with personalization', [], [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'UX Designer', count: 2, geo: 'india' }], ['CX platform', 'Omnichannel integration', 'Personalization engine', 'Journey orchestration', 'Analytics'], ['Channel consistency', 'Data silos', 'Personalization accuracy'], '6-12 months', '$500K-$2M', ['CX', 'Omnichannel', 'Personalization', 'Journey'], 'Omnichannel customer experience with AI personalization and journey orchestration'),
  makeTemplate('dt-04', 'Supply Chain Digitalization', 'Digital Transformation', 'Fixed Price', ['Manufacturing', 'Retail', 'Energy'], 'Enterprise', 'End-to-end supply chain digitalization with visibility and predictive analytics', AI_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['Supply chain platform', 'Visibility dashboard', 'Predictive analytics', 'Supplier portal', 'Integration layer'], ['Data availability', 'Partner onboarding', 'Complexity', 'Change management'], '6-12 months', '$500K-$2M', ['Supply Chain', 'Visibility', 'Predictive'], 'Supply chain digitalization with real-time visibility and predictive analytics'),
  makeTemplate('dt-05', 'Workplace Modernization', 'Digital Transformation', 'Fixed Price', ['All'], 'Standard', 'Modern workplace with collaboration tools, productivity analytics, and automation', [], [{ role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['Collaboration platform', 'Productivity dashboards', 'Workflow automation', 'Training program', 'Adoption metrics'], ['User adoption', 'Security', 'Integration with legacy'], '2-4 months', '$100K-$400K', ['M365', 'Teams', 'Workplace', 'Productivity'], 'Workplace modernization with M365, collaboration, and intelligent automation'),

  // ═══════════════════════════════════════════
  // CONSULTING & ADVISORY (8 templates)
  // ═══════════════════════════════════════════
  makeTemplate('cons-01', 'Technology Due Diligence', 'Consulting & Advisory', 'Consulting', ['All'], 'Complex', 'Technical assessment for M&A, investment, or strategic decisions', [], [{ role: 'Technical Architect', count: 2, geo: 'us' }], ['Due diligence report', 'Risk assessment', 'Architecture review', 'Technical debt analysis', 'Recommendation deck'], ['Access to systems', 'Time constraints', 'Incomplete documentation'], '2-4 weeks', '$50K-$150K', ['Due Diligence', 'M&A', 'Assessment'], 'Technology due diligence for M&A with risk assessment and architecture review'),
  makeTemplate('cons-02', 'Architecture Review & Advisory', 'Consulting & Advisory', 'Consulting', ['All'], 'Standard', 'Expert review of existing architecture with recommendations', [], [{ role: 'Technical Architect', count: 1, geo: 'us' }], ['Architecture review', 'Findings report', 'Recommendations', 'Prioritized roadmap'], ['Access to documentation', 'Stakeholder availability'], '2-4 weeks', '$30K-$100K', ['Architecture Review', 'Advisory', 'Best Practices'], 'Architecture review with prioritized improvement recommendations'),
  makeTemplate('cons-03', 'Cloud Strategy & Assessment', 'Consulting & Advisory', 'Consulting', ['All'], 'Complex', 'Cloud readiness assessment with provider comparison and migration strategy', CLOUD_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'DevOps Engineer', count: 1, geo: 'india' }], ['Cloud assessment', 'Provider comparison', 'TCO analysis', 'Migration strategy', 'Governance recommendations'], ['Vendor bias', 'Complete inventory', 'Cost accuracy'], '4-8 weeks', '$80K-$200K', ['Cloud Strategy', 'Assessment', 'TCO'], 'Cloud strategy assessment with provider comparison and TCO analysis'),
  makeTemplate('cons-04', 'AI Readiness Assessment', 'Consulting & Advisory', 'Consulting', ['All'], 'Standard', 'Organizational AI readiness evaluation with use case prioritization', AI_SECTIONS, [{ role: 'AI/ML Engineer', count: 1, geo: 'us' }, { role: 'Business Analyst', count: 1, geo: 'india' }], ['AI readiness report', 'Use case catalog', 'Data maturity assessment', 'Roadmap', 'Quick wins'], ['Data availability', 'Skill assessment accuracy', 'Expectation management'], '4-6 weeks', '$50K-$150K', ['AI Readiness', 'Use Case', 'Data Maturity'], 'AI readiness assessment with use case prioritization and quick wins'),

  // ═══════════════════════════════════════════
  // CYBERSECURITY (8 templates)
  // ═══════════════════════════════════════════
  makeTemplate('sec-01', 'Zero Trust Architecture', 'Cybersecurity', 'Fixed Price', ['Financial Services', 'Healthcare', 'Government'], 'Enterprise', 'Zero trust security architecture implementation', SECURITY_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'DevOps Engineer', count: 2, geo: 'india' }], ['Zero trust architecture', 'Identity framework', 'Micro-segmentation', 'Monitoring setup', 'Policy documentation'], ['Legacy system integration', 'User experience impact', 'Tool complexity'], '4-8 months', '$300K-$1M', ['Zero Trust', 'IAM', 'Security', 'Micro-segmentation'], 'Zero trust architecture with identity-first security and micro-segmentation'),
  makeTemplate('sec-02', 'Compliance & Governance (SOC2/HIPAA/PCI)', 'Cybersecurity', 'Consulting', ['Financial Services', 'Healthcare', 'Technology'], 'Complex', 'Compliance program implementation with audit readiness', SECURITY_SECTIONS, [{ role: 'Business Analyst', count: 2, geo: 'india' }, { role: 'DevOps Engineer', count: 1, geo: 'india' }], ['Compliance framework', 'Control mapping', 'Evidence collection', 'Audit preparation', 'Remediation plan'], ['Scope definition', 'Evidence gathering', 'Ongoing maintenance'], '3-6 months', '$150K-$500K', ['SOC2', 'HIPAA', 'PCI', 'Compliance', 'Governance'], 'Compliance program with SOC2/HIPAA/PCI readiness and continuous monitoring'),
  makeTemplate('sec-03', 'Security Operations Center (SOC)', 'Cybersecurity', 'Managed Service', ['Financial Services', 'Healthcare', 'Government'], 'Enterprise', 'Managed SOC with SIEM, threat detection, and incident response', [...SECURITY_SECTIONS, ...MANAGED_SECTIONS], [{ role: 'DevOps Engineer', count: 4, geo: 'india' }, { role: 'Technical Architect', count: 1, geo: 'us' }], ['SOC operations', 'SIEM deployment', 'Threat playbooks', 'Incident response procedures', 'Compliance reports'], ['Alert fatigue', 'Threat landscape evolution', 'Talent retention'], '12+ months', '$500K-$2M/year', ['SOC', 'SIEM', 'Threat Detection', 'Incident Response'], 'Managed SOC with AI-driven threat detection and automated incident response'),
  makeTemplate('sec-04', 'Identity & Access Management', 'Cybersecurity', 'Fixed Price', ['All'], 'Complex', 'Enterprise IAM with SSO, MFA, PAM, and identity governance', SECURITY_SECTIONS, [{ role: 'Technical Architect', count: 1, geo: 'us' }, { role: 'Sr Full Stack Engineer', count: 2, geo: 'india' }], ['IAM architecture', 'SSO/MFA implementation', 'PAM setup', 'Identity governance', 'Access certification'], ['Legacy system integration', 'User experience', 'Provisioning complexity'], '3-6 months', '$200K-$600K', ['IAM', 'SSO', 'MFA', 'PAM', 'Identity'], 'Enterprise IAM with SSO, MFA, privileged access management, and governance'),

  // ═══════════════════════════════════════════
  // STAFF AUGMENTATION (8 templates)
  // ═══════════════════════════════════════════
  makeTemplate('staff-01', 'Development Team Augmentation', 'Staff Augmentation', 'Staff Augmentation', ['All'], 'Standard', 'Dedicated development team with full-stack engineers', [], [{ role: 'Sr Full Stack Engineer', count: 4, geo: 'india' }, { role: 'QA Engineer', count: 1, geo: 'india' }], ['Onboarded team', 'Knowledge documentation', 'Sprint reports', 'Velocity metrics'], ['Ramp-up time', 'Cultural fit', 'Knowledge transfer'], '6-12+ months', '$300K-$800K/year', ['Staff Aug', 'Development Team', 'Dedicated'], 'Dedicated development team with senior engineers and sprint cadence'),
  makeTemplate('staff-02', 'DevOps Team Augmentation', 'Staff Augmentation', 'Staff Augmentation', ['All'], 'Standard', 'DevOps engineering team for infrastructure and automation', [], [{ role: 'DevOps Engineer', count: 3, geo: 'india' }], ['Onboarded team', 'Automation contributions', 'Monthly reports'], ['Tool familiarity', 'Security clearances', 'On-call requirements'], '6-12+ months', '$200K-$600K/year', ['DevOps Team', 'Staff Aug', 'Infrastructure'], 'DevOps team augmentation for infrastructure, automation, and CI/CD'),
  makeTemplate('staff-03', 'QA Team Augmentation', 'Staff Augmentation', 'Staff Augmentation', ['All'], 'Standard', 'QA and test automation team', [], [{ role: 'QA Engineer', count: 4, geo: 'india' }], ['Onboarded team', 'Test coverage metrics', 'Automation metrics'], ['Test environment access', 'Domain knowledge', 'Tool proficiency'], '6-12+ months', '$150K-$400K/year', ['QA Team', 'Staff Aug', 'Testing'], 'QA team augmentation for manual + automated testing'),
  makeTemplate('staff-04', 'Data Engineering Team', 'Staff Augmentation', 'Staff Augmentation', ['All'], 'Complex', 'Data engineering team for pipeline development and analytics', [], [{ role: 'Data Architect', count: 1, geo: 'india' }, { role: 'Sr Full Stack Engineer', count: 3, geo: 'india' }], ['Onboarded team', 'Pipeline documentation', 'Data quality reports'], ['Data access', 'Domain complexity', 'Tool stack alignment'], '6-12+ months', '$250K-$700K/year', ['Data Team', 'Staff Aug', 'Analytics'], 'Data engineering team for pipelines, analytics, and governance'),
];

// ── Lookup helpers ──

export const SERVICE_DOMAINS: ServiceDomain[] = [
  'AI & Data Engineering', 'Cloud & Infrastructure', 'Application Development',
  'Enterprise Architecture', 'ERP & Business Applications', 'Managed Services',
  'QA & Testing', 'DevSecOps', 'Digital Transformation', 'Consulting & Advisory',
  'Cybersecurity', 'Staff Augmentation',
];

export const ENGAGEMENT_TYPES: EngagementType[] = [
  'Fixed Price', 'Time & Material', 'Managed Service', 'Consulting', 'Staff Augmentation', 'Hybrid',
];

export const INDUSTRIES = [
  'Technology', 'Financial Services', 'Healthcare', 'Manufacturing',
  'Retail', 'Energy', 'Telecom', 'Government', 'Hospitality', 'Professional Services',
];

export const COMPLEXITY_LEVELS = ['Standard', 'Complex', 'Enterprise'] as const;

export function getTemplatesByDomain(domain: ServiceDomain): ProposalTemplate[] {
  return PROPOSAL_TEMPLATES.filter(t => t.domain === domain);
}

export function getTemplatesByIndustry(industry: string): ProposalTemplate[] {
  return PROPOSAL_TEMPLATES.filter(t => t.industries.includes(industry) || t.industries.includes('All'));
}

export function searchTemplates(query: string): ProposalTemplate[] {
  const q = query.toLowerCase();
  return PROPOSAL_TEMPLATES.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.tags.some(tag => tag.toLowerCase().includes(q)) ||
    t.domain.toLowerCase().includes(q)
  );
}

export function getTemplateById(id: string): ProposalTemplate | undefined {
  return PROPOSAL_TEMPLATES.find(t => t.id === id);
}
